// src/exporter.ts
import { App, TFile, MarkdownRenderer, Component, Notice, FileSystemAdapter, Modal, Setting } from 'obsidian';
import { getTemplate, PageData } from './template';
import { ExportHtmlSettings } from './settings';
import * as fs from 'fs';
import * as path from 'path';

interface ExportSettings {
    pageWidth: number;
    enableToc: boolean;
    tocPosition: 'right' | 'left';
    showTitle: boolean;
    showFooter: boolean;
    footerText: string;
    defaultTheme: 'light' | 'dark';
    showProperties: boolean;
    fontStyle: 'sans' | 'serif' | 'mono';
}

// 默认设置
const DEFAULT_SETTINGS: ExportSettings = {
    pageWidth: 960,
    enableToc: true,
    tocPosition: 'right',
    showTitle: true,
    showFooter: true,
    footerText: 'Generated by Export HTML',
    defaultTheme: 'light',
    showProperties: true,
    fontStyle: 'sans'
};

// 存储的键名
const STORAGE_KEY = 'export-html-settings';

class ExportSettingsModal extends Modal {
    settings: ExportSettings;
    files: TFile[];
    onSubmit: (settings: ExportSettings, files: TFile[]) => void;
    previewEl: HTMLElement;
    paperEl: HTMLElement;
    fileBarEl: HTMLElement;
    exportBtnEl: HTMLButtonElement;
    footerTextAreaEl: HTMLTextAreaElement | null = null;
    pluginSettings: ExportHtmlSettings;
    paperContentEl: HTMLElement;
    
    // 拖拽相关状态
    isDragging: boolean = false;
    dragStartX: number = 0;
    dragStartY: number = 0;
    paperStartX: number = 0;
    paperStartY: number = 0;
    currentTranslateX: number = 0;
    currentTranslateY: number = 0;
    currentScale: number = 1;

    constructor(app: App, files: TFile[], onSubmit: (settings: ExportSettings, files: TFile[]) => void, pluginSettings?: ExportHtmlSettings) {
        super(app);
        this.files = files;
        this.onSubmit = onSubmit;
        this.pluginSettings = pluginSettings || { excludedFolders: [] };
        // 从 localStorage 加载设置
        this.settings = this.loadSettings();
    }

    // 从 localStorage 加载设置
    loadSettings(): ExportSettings {
        try {
            const saved = localStorage.getItem(STORAGE_KEY);
            if (saved) {
                return { ...DEFAULT_SETTINGS, ...JSON.parse(saved) };
            }
        } catch (e) {
            console.error('加载设置失败:', e);
        }
        return { ...DEFAULT_SETTINGS };
    }

    // 保存设置到 localStorage
    saveSettings() {
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(this.settings));
        } catch (e) {
            console.error('保存设置失败:', e);
        }
    }

    onOpen() {
        const { contentEl } = this;
        contentEl.addClass('export-settings-modal');
        
        // 主容器 - 左右布局
        const mainContainer = contentEl.createDiv({ cls: 'export-main-container' });
        
        // 左侧设置区域
        const leftPanel = mainContainer.createDiv({ cls: 'export-left-panel' });
        
        // 1. 页面宽度设置
        new Setting(leftPanel)
            .setName('页面宽度')
            .setDesc('设置内容区域宽度（像素）')
            .setClass('export-page-width-setting')
            .addText(t => {
                t.setValue(String(this.settings.pageWidth))
                    .onChange(v => {
                        this.settings.pageWidth = parseInt(v) || 960;
                        this.updatePaperSize();
                        this.autoFitScale(); // 新增：修改宽度后立刻自适应
                        setTimeout(() => {
                            this.previewEl.scrollLeft = (this.previewEl.scrollWidth - this.previewEl.clientWidth) / 2;
                        }, 10);
                    });
                // 限制输入框宽度并居中
                t.inputEl.style.width = '80px';
                t.inputEl.style.textAlign = 'center';
                t.inputEl.style.minHeight = '28px';
            });

        // 2. 目录设置
        new Setting(leftPanel)
            .setName('启用目录导航')
            .setClass('export-toggle-setting')
            .addToggle(t => t.setValue(this.settings.enableToc)
                .onChange(v => {
                    this.settings.enableToc = v;
                    this.updatePreviewContent();
                }));

        new Setting(leftPanel)
            .setName('目录位置')
            .setClass('export-dropdown-setting')
            .addDropdown(d => d
                .addOption('right', '右侧')
                .addOption('left', '左侧')
                .setValue(this.settings.tocPosition)
                .onChange(v => {
                    this.settings.tocPosition = v as 'right' | 'left';
                    this.updatePreviewContent();
                }));

        // 3. 标题设置
        new Setting(leftPanel)
            .setName('显示标题')
            .setClass('export-toggle-setting')
            .addToggle(t => t.setValue(this.settings.showTitle)
                .onChange(v => {
                    this.settings.showTitle = v;
                    this.updatePreviewContent();
                }));

        // 4. 默认主题设置
        new Setting(leftPanel)
            .setName('默认主题模式')
            .setDesc('导出页面的初始主题')
            .setClass('export-dropdown-setting')
            .addDropdown(d => d
                .addOption('light', '浅色 Light')
                .addOption('dark', '深色 Dark')
                .setValue(this.settings.defaultTheme)
                .onChange(v => {
                    this.settings.defaultTheme = v as 'light' | 'dark';
                    this.updatePreviewStyles();
                }));

        // 5. 文档属性设置
        new Setting(leftPanel)
            .setName('显示文档属性')
            .setDesc('显示 YAML Frontmatter 属性')
            .setClass('export-toggle-setting')
            .addToggle(t => t.setValue(this.settings.showProperties)
                .onChange(v => {
                    this.settings.showProperties = v;
                    this.updatePreviewContent();
                }));

        // 6. 字体风格设置
        new Setting(leftPanel)
            .setName('字体风格')
            .setClass('export-dropdown-setting')
            .addDropdown(d => d
                .addOption('sans', '无衬线 Sans-serif')
                .addOption('serif', '衬线 Serif')
                .addOption('mono', '等宽 Mono')
                .setValue(this.settings.fontStyle)
                .onChange(v => {
                    this.settings.fontStyle = v as 'sans' | 'serif' | 'mono';
                    this.updatePreviewStyles();
                }));

        // 7. 页脚设置（移到最后）
        new Setting(leftPanel)
            .setName('显示页脚')
            .setClass('export-toggle-setting')
            .addToggle(t => t.setValue(this.settings.showFooter)
                .onChange(v => {
                    this.settings.showFooter = v;
                    this.updatePreviewContent();
                }));

        new Setting(leftPanel)
            .setName('页脚文本')
            .setClass('export-footer-text-setting')
            .addTextArea(t => {
                t.setValue(this.settings.footerText)
                    .onChange(v => {
                        this.settings.footerText = v;
                        this.updatePreviewContent();
                    });
                t.inputEl.style.width = '100%';
                t.inputEl.style.minHeight = '60px';
                t.inputEl.style.resize = 'vertical';
                t.inputEl.rows = 2;
                // 保存 textarea 引用，用于记录高度
                this.footerTextAreaEl = t.inputEl;
                // 如果有保存的高度，应用它
                const savedHeight = localStorage.getItem('export-html-footer-height');
                if (savedHeight) {
                    t.inputEl.style.height = savedHeight;
                }
                // 监听高度变化并保存
                t.inputEl.addEventListener('mouseup', () => {
                    if (t.inputEl.style.height) {
                        localStorage.setItem('export-html-footer-height', t.inputEl.style.height);
                    }
                });
            });
        
        // 右侧预览区域
        const rightPanel = mainContainer.createDiv({ cls: 'export-right-panel' });
        rightPanel.createEl('h3', { text: '预览', cls: 'export-section-title' });
        
        // 预览容器（灰色背景）
        this.previewEl = rightPanel.createDiv({ cls: 'export-preview-container' });
        
        // 可拖动的白纸
        this.paperEl = this.previewEl.createDiv({ cls: 'export-preview-paper' });
        
        // 初始化白纸大小
        this.updatePaperSize();

        // 初始化拖拽功能
        this.initDragFunctionality();

        // 异步更新预览内容
        this.updatePreviewContent();

        // 初始化预览样式（主题和字体）
        this.updatePreviewStyles();
        
        // 文件选择栏（在预览下方）
        this.fileBarEl = rightPanel.createDiv({ cls: 'export-file-bar' });
        this.updateFileBar();
        
        // 底部按钮区域
        const buttonContainer = contentEl.createDiv({ cls: 'export-button-container' });
        
        buttonContainer.createEl('button', { 
            text: '取消', 
            cls: 'export-btn export-btn-cancel'
        }).addEventListener('click', () => this.close());
        
        this.exportBtnEl = buttonContainer.createEl('button', {
            text: `导出`,
            cls: 'export-btn export-btn-primary'
        }) as HTMLButtonElement;
        this.exportBtnEl.addEventListener('click', () => {
            if (this.files.length === 0) {
                new Notice('请先添加文件');
                return;
            }
            // 保存设置
            this.saveSettings();
            this.close();
            this.onSubmit(this.settings, this.files);
        });
        this.updateExportButton();
        
        // 添加样式
        this.addStyles();
    }
    
    updatePaperSize() {
        if (!this.paperEl) return;
        const width = this.settings.pageWidth;
        this.paperEl.style.width = width + 'px';
    }

    async updatePreviewContent() {
        if (!this.paperEl || !this.previewEl) return;

        // 1. 渲染前先隐藏纸张，取消所有过渡动画，防止闪烁
        this.paperEl.style.transition = 'none';
        this.paperEl.style.opacity = '0';

        // 改为保存外层容器(previewEl)的当前滚动位置
        const savedScrollTop = this.previewEl.scrollTop;
        const savedScrollLeft = this.previewEl.scrollLeft;

        // 清空现有内容
        this.paperEl.empty();

        // 如果启用目录，先创建模拟目录（在内容容器之外，确保跟随拖拽）
        if (this.settings.enableToc) {
            this.createMockToc();
        }

        // 创建内容容器
        this.paperContentEl = this.paperEl.createDiv({ cls: 'paper-content' });

        // 如果有选中的文件，渲染第一个文件的内容
        if (this.files.length > 0) {
            const firstFile = this.files[0]!;
            try {
                // 读取文件内容
                let content = await this.app.vault.read(firstFile);

                // 处理 Frontmatter
                const frontmatterMatch = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n/);
                let frontmatter: Record<string, string> | null = null;

                if (frontmatterMatch && frontmatterMatch[1]) {
                    // 解析 Frontmatter
                    frontmatter = this.parseFrontmatter(frontmatterMatch[1]);
                    // 如果不显示属性，移除 Frontmatter
                    if (!this.settings.showProperties) {
                        content = content.substring(frontmatterMatch[0].length);
                    }
                }



                // 创建临时容器用于渲染
                const tempContainer = document.createElement('div');
                tempContainer.style.display = 'none';
                document.body.appendChild(tempContainer);

                // 使用 MarkdownRenderer 渲染内容
                await MarkdownRenderer.render(this.app, content, tempContainer, firstFile.path, new Component());

                // 将渲染后的内容移动到预览区域
                if (this.settings.showTitle) {
                    this.paperContentEl.createEl('h1', { text: firstFile.basename, cls: 'paper-title' });
                }

                // 显示文档属性（如果启用且有 Frontmatter）
                if (this.settings.showProperties && frontmatter && Object.keys(frontmatter).length > 0) {
                    this.renderProperties(frontmatter);
                }

                // 复制渲染后的内容
                const renderedContent = tempContainer.innerHTML;
                const contentDiv = this.paperContentEl.createDiv({ cls: 'paper-rendered-content' });
                contentDiv.innerHTML = renderedContent;

                // 清理临时容器
                tempContainer.remove();

                // 更新模拟目录（根据实际渲染后的标题）
                if (this.settings.enableToc) {
                    this.updateMockTocFromContent();
                }

            } catch (error) {
                console.error('预览渲染失败:', error);
                // 渲染失败时显示错误信息
                this.paperContentEl.createEl('p', {
                    text: '无法加载预览内容，请检查文件是否有效。',
                    cls: 'paper-error'
                });
            }
        } else {
            // 没有选中文件时显示提示
            this.paperContentEl.createEl('div', {
                text: '暂无文件，请添加文件以查看预览',
                cls: 'paper-empty'
            });
        }

        // 添加页脚（如果启用）
        if (this.settings.showFooter) {
            this.paperEl.createDiv({
                text: this.settings.footerText,
                cls: 'paper-footer'
            });
        }

        // 2. 同步执行自适应缩放（必须放在 setTimeout 之外，在浏览器下一次重绘前完成计算）
        if (savedScrollLeft === 0) {
            this.autoFitScale();
        }

        // 3. 恢复滚动条位置并平滑显示内容
        setTimeout(() => {
            if (!this.previewEl) return;

            // 恢复垂直滚动
            this.previewEl.scrollTop = savedScrollTop;

            // 恢复/初始化水平滚动
            if (savedScrollLeft === 0) {
                this.previewEl.scrollLeft = (this.previewEl.scrollWidth - this.previewEl.clientWidth) / 2;
            } else {
                this.previewEl.scrollLeft = savedScrollLeft;
            }

            // 所有布局计算完毕，开启渐显动画，彻底告别闪烁
            this.paperEl.style.transition = 'opacity 0.2s ease-in-out';
            this.paperEl.style.opacity = '1';
        }, 50);
    }

    // 解析 Frontmatter
    parseFrontmatter(yamlContent: string): Record<string, string> {
        const result: Record<string, string> = {};
        const lines = yamlContent.split('\n');
        for (const line of lines) {
            const match = line.match(/^([^:]+):\s*(.*)$/);
            if (match && match[1] && match[2]) {
                const key = match[1].trim();
                const value = match[2].trim().replace(/^["']|["']$/g, '');
                result[key] = value;
            }
        }
        return result;
    }

    // 渲染文档属性
    renderProperties(frontmatter: Record<string, string>) {
        const propsContainer = this.paperContentEl.createDiv({ cls: 'paper-properties' });

        for (const [key, value] of Object.entries(frontmatter)) {
            const propItem = propsContainer.createDiv({ cls: 'paper-property-item' });
            propItem.createEl('span', { text: key, cls: 'paper-property-key' });
            propItem.createEl('span', { text: value, cls: 'paper-property-value' });
        }
    }

    // 更新预览样式（主题和字体）
    updatePreviewStyles() {
        if (!this.paperEl) return;

        // 应用字体风格
        const fontFamily = this.settings.fontStyle === 'serif'
            ? 'Georgia, "Times New Roman", serif'
            : this.settings.fontStyle === 'mono'
                ? '"SF Mono", Monaco, "Cascadia Code", "Roboto Mono", Consolas, "Courier New", monospace'
                : '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif';
        this.paperEl.style.fontFamily = fontFamily;

        // 应用主题
        if (this.settings.defaultTheme === 'dark') {
            this.paperEl.classList.add('theme-dark-preview');
        } else {
            this.paperEl.classList.remove('theme-dark-preview');
        }
    }

    // 创建模拟目录
    createMockToc() {
        const tocEl = this.paperEl.createDiv({
            cls: `mock-toc mock-toc-${this.settings.tocPosition}`
        });

        // 创建骨架屏样式的目录项
        const tocItems = [
            { level: 1, width: '60%' },
            { level: 2, width: '45%' },
            { level: 2, width: '50%' },
            { level: 3, width: '35%' },
            { level: 1, width: '55%' },
            { level: 2, width: '40%' }
        ];

        tocItems.forEach((item, index) => {
            const line = tocEl.createDiv({
                cls: `mock-toc-line mock-toc-level-${item.level}`
            });
            line.style.width = item.width;
        });
    }

    // 根据实际内容更新模拟目录
    updateMockTocFromContent() {
        const tocEl = this.paperEl.querySelector('.mock-toc');
        if (!tocEl) return;

        // 获取实际渲染的标题
        const headers = this.paperContentEl.querySelectorAll('h1, h2, h3, h4, h5, h6');
        if (headers.length === 0) return;

        // 清空现有模拟目录
        tocEl.empty();

        // 根据实际标题生成模拟目录
        headers.forEach((header, index) => {
            const level = parseInt(header.tagName.substring(1));
            const width = Math.max(30, 70 - (level - 1) * 10) + '%';

            const line = tocEl.createDiv({
                cls: `mock-toc-line mock-toc-level-${Math.min(level, 3)}`
            });
            line.style.width = width;
        });
    }

    initDragFunctionality() {
        if (!this.paperEl || !this.previewEl) return;

        // 设置初始光标样式
        this.paperEl.style.cursor = 'grab';

        // 鼠标按下事件
        this.paperEl.addEventListener('mousedown', (e: MouseEvent) => {
            this.isDragging = true;
            this.dragStartX = e.clientX;
            this.dragStartY = e.clientY;

            // 改变光标样式
            this.paperEl.style.cursor = 'grabbing';
            this.paperEl.classList.add('dragging');

            // 阻止默认行为（防止选中文本）
            e.preventDefault();
        });

        // 鼠标移动事件（混合拖拽：原生滚动优先，剩余交给 Transform）
        this.previewEl.addEventListener('mousemove', (e: MouseEvent) => {
            if (!this.isDragging) return;

            const deltaX = e.clientX - this.dragStartX;
            const deltaY = e.clientY - this.dragStartY;

            // 逐帧更新起始点，实现平滑的连续计算
            this.dragStartX = e.clientX;
            this.dragStartY = e.clientY;

            // 1. 优先尝试让原生滚动条来吸收位移
            const oldScrollLeft = this.previewEl.scrollLeft;
            const oldScrollTop = this.previewEl.scrollTop;

            this.previewEl.scrollLeft -= deltaX;
            this.previewEl.scrollTop -= deltaY;

            // 计算滚动条实际消化了多少位移
            const actualScrollX = oldScrollLeft - this.previewEl.scrollLeft;
            const actualScrollY = oldScrollTop - this.previewEl.scrollTop;

            // 2. 滚动条无法消化的部分（无滚动条或触达边界），交给 Transform 平移
            const remainingX = deltaX - actualScrollX;
            const remainingY = deltaY - actualScrollY;

            this.currentTranslateX += remainingX;
            this.currentTranslateY += remainingY;

            this.updatePaperTransform();
        });

        // 鼠标释放事件
        const handleMouseUp = () => {
            if (!this.isDragging) return;

            this.isDragging = false;
            this.paperEl.style.cursor = 'grab';
            this.paperEl.classList.remove('dragging');
        };

        this.previewEl.addEventListener('mouseup', handleMouseUp);
        this.previewEl.addEventListener('mouseleave', handleMouseUp);

        // 双击重置位置与大小
        this.previewEl.addEventListener('dblclick', () => {
            this.autoFitScale(); // 修改：从 this.currentScale = 1 改为自适应
            this.currentTranslateX = 0;
            this.currentTranslateY = 0;
            this.updatePaperTransform();
            // 让滚动条回到中心附近
            this.previewEl.scrollLeft = (this.previewEl.scrollWidth - this.previewEl.clientWidth) / 2;
            this.previewEl.scrollTop = 0;
        });

        // Ctrl + 滚轮缩放画布 (以鼠标为中心缩放)
        this.previewEl.addEventListener('wheel', (e: WheelEvent) => {
            if (e.ctrlKey || e.metaKey) {
                e.preventDefault();

                // 1. 获取鼠标相对于外层可视容器(previewEl)的局部坐标
                const rect = this.previewEl.getBoundingClientRect();
                const mouseX = e.clientX - rect.left;
                const mouseY = e.clientY - rect.top;

                // 2. 计算新旧缩放比例
                const oldScale = this.currentScale;
                const zoomAmount = e.deltaY > 0 ? -0.1 : 0.1;
                const newScale = Math.max(0.3, Math.min(3.0, oldScale + zoomAmount));

                if (oldScale === newScale) return;

                // 3. 核心数学公式：计算缩放后需要补偿的滚动距离
                // 原理：(鼠标位置 + 原滚动距离) * (新缩放率 / 旧缩放率) - 鼠标位置
                const ratio = newScale / oldScale;
                const newScrollLeft = (mouseX + this.previewEl.scrollLeft) * ratio - mouseX;
                const newScrollTop = (mouseY + this.previewEl.scrollTop) * ratio - mouseY;

                // 4. 应用新的缩放比例
                this.currentScale = newScale;
                this.updatePaperTransform();

                // 5. 立即补偿滚动条位置，使鼠标所指的视觉锚点保持绝对静止
                this.previewEl.scrollLeft = newScrollLeft;
                this.previewEl.scrollTop = newScrollTop;
            }
        });
    }

    updatePaperTransform() {
        if (!this.paperEl) return;
        // zoom 负责内容缩放（联动原生滚动条），transform 负责处理溢出边缘的自由平移
        this.paperEl.style.zoom = String(this.currentScale);
        this.paperEl.style.transform = `translate(${this.currentTranslateX}px, ${this.currentTranslateY}px)`;
    }

    autoFitScale() {
        if (!this.previewEl || !this.paperEl) return;

        // 容器可用宽度 = 容器实际宽度 - 左右 padding(80px) - 安全余量(20px)
        const availableWidth = this.previewEl.clientWidth - 100;
        if (availableWidth <= 0) return;

        // 计算刚好能完整显示白纸的缩放比例
        const targetScale = availableWidth / this.settings.pageWidth;

        // 限制在允许的缩放范围内
        this.currentScale = Math.max(0.3, Math.min(3.0, targetScale));
        this.updatePaperTransform();
    }

    updateFileBar() {
        if (!this.fileBarEl) return;

        let html = '<div class="file-bar-scroll-container">';

        if (this.files.length === 0) {
            html += '<span class="file-bar-empty">暂无文件，点击右侧 + 添加</span>';
        } else {
            this.files.forEach((file, index) => {
                // 获取从仓库根目录开始的路径（不包含仓库名）
                const displayPath = file.path;
                html += `
                    <span class="file-bar-item" title="${displayPath}">
                        <span class="file-bar-name">${file.basename}</span>
                        <span class="file-bar-remove" data-index="${index}" title="移除">×</span>
                    </span>
                `;
            });
        }

        html += '</div>';
        html += `<button class="file-bar-add-btn" title="添加文件">+</button>`;

        this.fileBarEl.innerHTML = html;

        // 绑定添加按钮事件
        const addBtn = this.fileBarEl.querySelector('.file-bar-add-btn');
        if (addBtn) {
            addBtn.addEventListener('click', () => this.openFileSelector());
        }

        // 绑定删除按钮事件
        const removeBtns = this.fileBarEl.querySelectorAll('.file-bar-remove');
        removeBtns.forEach(btn => {
            btn.addEventListener('click', (e) => {
                e.stopPropagation();
                const index = parseInt((btn as HTMLElement).dataset.index || '0');
                this.files.splice(index, 1);
                this.updateFileBar();
                this.updateExportButton();
            });
        });
    }

    showAllFiles() {
        // 显示所有文件的弹窗
        new AllFilesModal(this.app, this.files, (newFiles) => {
            this.files = newFiles;
            this.updateFileBar();
            this.updateExportButton();
        }).open();
    }
    
    updateExportButton() {
        if (!this.exportBtnEl) return;
        
        if (this.files.length === 0) {
            this.exportBtnEl.textContent = '导出';
            this.exportBtnEl.disabled = true;
            this.exportBtnEl.style.opacity = '0.5';
            this.exportBtnEl.style.cursor = 'not-allowed';
        } else {
            this.exportBtnEl.textContent = `导出 (${this.files.length} 个文件)`;
            this.exportBtnEl.disabled = false;
            this.exportBtnEl.style.opacity = '1';
            this.exportBtnEl.style.cursor = 'pointer';
        }
    }
    
    openFileSelector() {
        // 获取所有 markdown 文件
        let allFiles = this.app.vault.getFiles().filter(f => f.extension === 'md');
        
        // 应用排除文件夹规则
        if (this.pluginSettings.excludedFolders && this.pluginSettings.excludedFolders.length > 0) {
            allFiles = allFiles.filter(file => {
                // 检查文件路径是否以排除的文件夹开头
                return !this.pluginSettings.excludedFolders.some(folder => {
                    return file.path.startsWith(folder + '/') || file.path === folder;
                });
            });
        }
        
        // 打开文件选择弹窗，传入所有文件和已选文件
        new FileSelectorModal(this.app, allFiles, this.files, (selectedFiles) => {
            this.files = selectedFiles;
            this.updateFileBar();
            this.updateExportButton();
        }).open();
    }
    
    addStyles() {
        const style = document.createElement('style');
        style.setAttribute('data-export-settings', 'true');
        style.textContent = `
            /* 强制覆盖 Obsidian 默认弹窗样式 */
            .modal-container:has(.export-settings-modal) .modal {
                width: 950px !important;
                max-width: 95vw !important;
                height: 580px !important;
                max-height: 90vh !important;
            }
            .modal-container:has(.export-settings-modal) {
                align-items: center !important;
                justify-content: center !important;
            }
            /* 修复选择器层级错误 - 使用同级选择器 */
            .modal-content.export-settings-modal {
                display: flex;
                flex-direction: column;
                overflow: hidden !important;
                padding: 0 !important;
            }
            /* 主体容器 - 左右布局，占据剩余空间 */
            .export-main-container {
                flex: 1;
                min-height: 0;
                display: flex;
                flex-direction: row;
                overflow: hidden;
            }
            /* 底部按钮 - 永久固定在底部 */
            .export-button-container {
                flex-shrink: 0;
                padding: 16px 20px;
                border-top: 1px solid var(--background-modifier-border);
                display: flex;
                justify-content: flex-end;
                gap: 12px;
                background: transparent;
                z-index: 10;
            }
            /* 左侧面板 - 恢复 Obsidian 原生排版 */
            .export-left-panel {
                flex: 0 0 340px;
                overflow-y: auto;
                padding: 20px;
                border-right: 1px solid var(--background-modifier-border);
            }
            /* 自定义细滚动条 */
            .export-left-panel::-webkit-scrollbar {
                width: 4px;
            }
            .export-left-panel::-webkit-scrollbar-track {
                background: transparent;
            }
            .export-left-panel::-webkit-scrollbar-thumb {
                background: var(--background-modifier-border);
                border-radius: 2px;
            }
            .export-left-panel::-webkit-scrollbar-thumb:hover {
                background: var(--text-muted);
            }
            /* 右侧面板 */
            .export-right-panel {
                flex: 1;
                padding: 20px;
                overflow: hidden;
                display: flex;
                flex-direction: column;
            }
            .export-section-title {
                margin: 0 0 8px 0;
                font-size: 13px;
                font-weight: 600;
                color: var(--text-normal);
            }
            /* 预览容器（灰色背景） */
            .export-preview-container {
                display: flex;
                flex-direction: column;
                overflow: auto;
                padding: 40px;
                position: relative;
                background: var(--background-secondary);
                border-radius: 8px;
                flex: 1;
                min-height: 0;
            }
            /* 可拖动的白纸 */
            .export-preview-paper {
                margin: auto !important;
                flex-shrink: 0;
                background: var(--background-primary);
                border-radius: 4px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.1);
                height: max-content;
                padding: 20px;
                display: block;
                user-select: none;
                transform-origin: center center;
                text-align: left !important;
                transition: box-shadow 0.2s ease;
            }
            .export-preview-paper.dragging {
                box-shadow: 0 8px 24px rgba(0,0,0,0.15);
                transition: width 0.3s ease, box-shadow 0.2s ease;
            }
            .export-preview-paper:active {
                cursor: grabbing;
            }
            .paper-title {
                margin: 0 0 16px 0;
                font-size: 1.5em;
                font-weight: 600;
                color: var(--text-normal);
                border-bottom: 1px solid var(--background-modifier-border);
                padding-bottom: 12px;
                text-align: left !important;
            }
            .paper-rendered-content {
                font-size: 0.9em;
                line-height: 1.6;
                text-align: left !important;
            }
            .paper-rendered-content h1,
            .paper-rendered-content h2,
            .paper-rendered-content h3,
            .paper-rendered-content h4,
            .paper-rendered-content h5,
            .paper-rendered-content h6 {
                margin: 12px 0 8px 0;
                font-weight: 600;
                text-align: left !important;
            }
            .paper-rendered-content p {
                margin: 8px 0;
                text-align: left !important;
            }
            .paper-rendered-content ul,
            .paper-rendered-content ol {
                margin: 8px 0;
                padding-left: 20px;
            }
            .paper-rendered-content li {
                margin: 4px 0;
            }
            .paper-rendered-content code {
                background: var(--background-secondary);
                padding: 2px 4px;
                border-radius: 3px;
                font-family: var(--font-monospace);
                font-size: 0.85em;
            }
            .paper-rendered-content pre {
                background: var(--background-secondary);
                padding: 12px;
                border-radius: 6px;
                overflow-x: auto;
                margin: 12px 0;
            }
            .paper-rendered-content pre code {
                background: transparent;
                padding: 0;
            }
            .paper-rendered-content blockquote {
                border-left: 3px solid var(--interactive-accent);
                margin: 12px 0;
                padding-left: 12px;
                color: var(--text-muted);
            }
            .paper-rendered-content img {
                max-width: 100%;
                border-radius: 4px;
                margin: 12px 0;
            }
            .paper-rendered-content table {
                width: 100%;
                border-collapse: collapse;
                margin: 12px 0;
            }
            .paper-rendered-content th,
            .paper-rendered-content td {
                border: 1px solid var(--background-modifier-border);
                padding: 6px 10px;
                text-align: left;
            }
            .paper-rendered-content th {
                background: var(--background-secondary);
                font-weight: 600;
            }
            .paper-empty {
                color: var(--text-muted);
                font-style: italic;
                text-align: center;
                padding: 40px 20px;
            }
            .paper-error {
                color: var(--text-error);
                text-align: center;
                padding: 40px 20px;
            }
            /* 深色主题预览样式 */
            .theme-dark-preview {
                background: #191919 !important;
                color: #d4d4d4 !important;
            }
            .theme-dark-preview .paper-title {
                color: #d4d4d4 !important;
                border-bottom-color: #2f2f2f !important;
            }
            .theme-dark-preview .paper-rendered-content {
                color: #d4d4d4 !important;
            }
            .theme-dark-preview .paper-rendered-content h1,
            .theme-dark-preview .paper-rendered-content h2,
            .theme-dark-preview .paper-rendered-content h3,
            .theme-dark-preview .paper-rendered-content h4,
            .theme-dark-preview .paper-rendered-content h5,
            .theme-dark-preview .paper-rendered-content h6 {
                color: #d4d4d4 !important;
            }
            .theme-dark-preview .paper-rendered-content p {
                color: #d4d4d4 !important;
            }
            .theme-dark-preview .paper-rendered-content code {
                background: #262626 !important;
                color: #ff9580 !important;
            }
            .theme-dark-preview .paper-rendered-content pre {
                background: #262626 !important;
            }
            .theme-dark-preview .paper-rendered-content blockquote {
                border-left-color: #3f3f3f !important;
                color: #9b9b9b !important;
            }
            .theme-dark-preview .paper-rendered-content th,
            .theme-dark-preview .paper-rendered-content td {
                border-color: #2f2f2f !important;
            }
            .theme-dark-preview .paper-rendered-content th {
                background: #202020 !important;
            }
            .theme-dark-preview .paper-properties {
                background: #202020 !important;
                border-color: #2f2f2f !important;
            }
            .theme-dark-preview .paper-property-key {
                color: #9b9b9b !important;
            }
            .theme-dark-preview .paper-property-value {
                color: #d4d4d4 !important;
            }
            .theme-dark-preview .paper-footer {
                border-top-color: #2f2f2f !important;
                color: #9b9b9b !important;
            }
            .theme-dark-preview .mock-toc {
                background: #202020 !important;
            }
            .theme-dark-preview .mock-toc-line {
                background: #3f3f3f !important;
            }
            .theme-dark-preview .mock-toc-level-1 {
                background: #5a5a5a !important;
            }
            .paper-content h2 {
                margin: 0 0 12px 0;
                font-size: 1.3em;
            }
            .paper-content p {
                margin: 0 0 12px 0;
                line-height: 1.5;
                font-size: 0.9em;
            }
            .paper-settings {
                margin: 12px 0;
                padding: 10px;
                background: var(--background-secondary);
                border-radius: 4px;
                font-size: 0.85em;
            }
            .paper-settings strong {
                display: block;
                margin-bottom: 4px;
            }
            .paper-footer {
                margin-top: 16px;
                padding-top: 12px;
                border-top: 1px solid var(--background-modifier-border);
                text-align: center;
                color: var(--text-muted);
                font-size: 0.8em;
                white-space: pre-line;
            }
            /* 模拟目录样式 */
            .mock-toc {
                position: absolute;
                top: 50%;
                transform: translateY(-50%);
                width: 80px;
                display: flex;
                flex-direction: column;
                gap: 8px;
                padding: 12px;
                background: var(--background-secondary);
                border-radius: 6px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.08);
                z-index: 10;
            }
            .mock-toc-left {
                left: 20px;
                right: auto;
            }
            .mock-toc-right {
                right: 20px;
                left: auto;
            }
            .mock-toc-line {
                height: 6px;
                background: var(--background-modifier-border);
                border-radius: 3px;
                transition: all 0.2s ease;
            }
            .mock-toc-level-1 {
                height: 8px;
                background: var(--text-muted);
            }
            .mock-toc-level-2 {
                height: 6px;
                margin-left: 8px;
                background: var(--text-faint);
            }
            .mock-toc-level-3 {
                height: 5px;
                margin-left: 16px;
                background: var(--text-faint);
                opacity: 0.7;
            }
            /* 文档属性样式 */
            .paper-properties {
                margin: 0 0 20px 0;
                padding: 12px 16px;
                background: var(--background-secondary);
                border-radius: 8px;
                border: 1px solid var(--background-modifier-border);
                display: flex;
                flex-direction: column;
                gap: 8px;
            }
            .paper-property-item {
                display: flex;
                align-items: center;
                gap: 12px;
                font-size: 0.85em;
            }
            .paper-property-key {
                color: var(--text-muted);
                font-weight: 500;
                min-width: 80px;
                text-transform: capitalize;
            }
            .paper-property-value {
                color: var(--text-normal);
                flex: 1;
            }
            /* 文件选择栏 - 流光边框特效 */
            .export-file-bar {
                display: flex;
                align-items: center;
                gap: 8px;
                padding: 10px 12px;
                border-radius: 6px;
                margin-top: 15px;
                min-height: 40px;
                flex-shrink: 0;
                position: relative;
                z-index: 1;
                overflow: hidden;
            }

            /* 旋转的流光渐变层 - 无缝连续双轨赛车特效 */
            .export-file-bar::before {
                content: '';
                position: absolute;
                top: 50%;
                left: 50%;
                width: 2500px;
                height: 2500px;
                transform: translate(-50%, -50%);
                background: conic-gradient(#ff4500, #ffa800, #ffd633, #9ccc65, #00ced1, #1e90ff, #c678dd, #ff4500);
                animation: border-flow 4s linear infinite;
                z-index: -2;
            }

            /* 内部背景层，遮盖中心区域，只露出 1px 宽度的流光边框 */
            .export-file-bar::after {
                content: '';
                position: absolute;
                inset: 1px;
                background: var(--background-secondary);
                border-radius: 5px;
                z-index: -1;
            }

            /* 流光旋转动画 - 无缝连续 */
            @keyframes border-flow {
                0% { transform: translate(-50%, -50%) rotate(0deg); }
                100% { transform: translate(-50%, -50%) rotate(360deg); }
            }
            .file-bar-scroll-container {
                display: flex;
                align-items: center;
                gap: 8px;
                overflow-x: scroll;
                flex-wrap: nowrap;
                flex: 1;
                scrollbar-width: none;
                -ms-overflow-style: none;
            }
            .file-bar-scroll-container::-webkit-scrollbar {
                display: none;
            }
            .file-bar-empty {
                color: var(--text-muted);
                font-size: 12px;
                flex: 1;
            }
            .file-bar-item {
                background: var(--background-primary);
                padding: 4px 8px 4px 10px;
                border-radius: 12px;
                font-size: 12px;
                white-space: nowrap;
                border: 1px solid var(--background-modifier-border);
                display: flex;
                align-items: center;
                gap: 6px;
                position: relative;
                flex-shrink: 0;
            }
            .file-bar-name {
                max-width: 120px;
                overflow: hidden;
                text-overflow: ellipsis;
            }
            .file-bar-remove {
                width: 16px;
                height: 16px;
                border-radius: 50%;
                background: var(--background-secondary);
                color: var(--text-muted);
                display: flex;
                align-items: center;
                justify-content: center;
                cursor: pointer;
                font-size: 14px;
                line-height: 1;
                opacity: 0;
                transition: opacity 0.2s;
                flex-shrink: 0;
            }
            .file-bar-item:hover .file-bar-remove {
                opacity: 1;
            }
            .file-bar-remove:hover {
                background: var(--text-error);
                color: white;
            }
            .file-bar-add-btn {
                width: 24px !important;
                height: 24px !important;
                min-width: 24px !important;
                min-height: 24px !important;
                max-width: 24px !important;
                max-height: 24px !important;
                border-radius: 50% !important;
                border: 1px dashed var(--background-modifier-border);
                background: transparent;
                color: var(--text-muted);
                cursor: pointer;
                font-size: 16px;
                line-height: 1;
                display: flex;
                align-items: center;
                justify-content: center;
                flex-shrink: 0;
                padding: 0 !important;
                margin: 0 !important;
                box-sizing: border-box !important;
                aspect-ratio: 1 / 1 !important;
            }
            .file-bar-add-btn:hover {
                border-color: var(--interactive-accent);
                color: var(--interactive-accent);
            }
            .export-btn {
                padding: 6px 20px;
                border-radius: 6px;
                border: 1px solid var(--background-modifier-border);
                cursor: pointer;
                font-size: 13px;
                transition: all 0.2s;
            }
            .export-btn-cancel {
                background: var(--background-primary);
                color: var(--text-normal);
            }
            .export-btn-cancel:hover {
                background: var(--background-modifier-hover);
            }
            .export-btn-primary {
                background: var(--interactive-accent);
                color: var(--text-on-accent);
                border-color: var(--interactive-accent);
            }
            .export-btn-primary:hover:not(:disabled) {
                background: var(--interactive-accent-hover);
            }
            /* 页脚文本设置 - 纵向排版 */
            .export-footer-text-setting {
                display: flex;
                flex-direction: column;
                align-items: flex-start;
            }
            .export-footer-text-setting .setting-item-info,
            .export-footer-text-setting .setting-item-control {
                width: 100%;
            }
            .export-footer-text-setting .setting-item-control {
                margin-top: 8px;
                justify-content: flex-start;
            }
            /* 页面宽度设置 - 输入框限制 */
            .export-page-width-setting input[type="text"] {
                width: 80px !important;
                text-align: center !important;
                min-height: 28px !important;
                border-radius: 4px !important;
                border: 1px solid var(--background-modifier-border) !important;
                background: var(--background-primary) !important;
                font-size: 13px !important;
            }
            .export-page-width-setting input[type="text"]:focus {
                border-color: var(--interactive-accent) !important;
                outline: none !important;
            }
            /* Toggle 开关样式 */
            .export-toggle-setting .setting-item-control {
                padding-right: 4px;
            }
            /* 下拉框样式 */
            .export-dropdown-setting select {
                min-height: 28px !important;
                border-radius: 4px !important;
                border: 1px solid var(--background-modifier-border) !important;
                background: var(--background-primary) !important;
                font-size: 13px !important;
                padding: 4px 8px !important;
                width: 100% !important;
            }
            .export-dropdown-setting select:focus {
                border-color: var(--interactive-accent) !important;
                outline: none !important;
            }
            /* 页脚文本输入框样式 */
            .export-footer-text-setting textarea {
                width: 100% !important;
                min-height: 60px !important;
                max-height: 120px !important;
                padding: 8px 10px !important;
                font-size: 12px !important;
                line-height: 1.4 !important;
                resize: vertical !important;
                border-radius: 6px !important;
                border: 1px solid var(--background-modifier-border) !important;
                background: var(--background-primary) !important;
                color: var(--text-normal) !important;
            }
            .export-footer-text-setting textarea:focus {
                border-color: var(--interactive-accent) !important;
                outline: none !important;
            }
        `;
        document.head.appendChild(style);
    }
    
    onClose() { 
        this.contentEl.empty();
        const style = document.querySelector('style[data-export-settings]');
        if (style) style.remove();
    }
}

// 文件选择弹窗（优化版）
class FileSelectorModal extends Modal {
    files: TFile[];
    selectedFiles: Set<TFile> = new Set();
    onSubmit: (files: TFile[]) => void;
    selectedListEl: HTMLElement;
    fileListContainer: HTMLElement;
    discoverBtnEl: HTMLButtonElement | null = null;

    constructor(app: App, files: TFile[], alreadySelected: TFile[], onSubmit: (files: TFile[]) => void) {
        super(app);
        this.files = files;
        this.onSubmit = onSubmit;
        // 初始化已选文件
        alreadySelected.forEach(f => this.selectedFiles.add(f));
    }

    onOpen() {
        const { contentEl } = this;
        contentEl.addClass('file-selector-modal');

        contentEl.createEl('h3', { text: '选择文件', cls: 'file-selector-title' });

        // 搜索框
        const searchBox = contentEl.createDiv({ cls: 'file-selector-search' });
        const searchInput = searchBox.createEl('input', {
            type: 'text',
            placeholder: '搜索文件...'
        });
        searchInput.addEventListener('input', () => {
            this.filterFiles(searchInput.value);
        });

        // 上方：可选文件列表
        contentEl.createEl('div', { text: '可选文件', cls: 'file-selector-section-title' });
        this.fileListContainer = contentEl.createDiv({ cls: 'file-selector-list' });
        this.renderFileList();

        // 下方：已选文件列表
        contentEl.createEl('div', { text: `已选择 (${this.selectedFiles.size})`, cls: 'file-selector-section-title selected-title' });
        this.selectedListEl = contentEl.createDiv({ cls: 'file-selector-selected-list' });
        this.updateSelectedList();

        // 按钮
        const buttonContainer = contentEl.createDiv({ cls: 'file-selector-buttons' });

        // 识别链接按钮
        this.discoverBtnEl = buttonContainer.createEl('button', {
            text: '识别链接',
            cls: 'export-btn export-btn-link'
        }) as HTMLButtonElement;
        this.discoverBtnEl.addEventListener('click', () => this.handleDiscoverLinks());
        this.updateDiscoverButton();

        buttonContainer.createEl('button', {
            text: '取消',
            cls: 'export-btn export-btn-cancel'
        }).addEventListener('click', () => this.close());

        buttonContainer.createEl('button', {
            text: '添加',
            cls: 'export-btn export-btn-primary'
        }).addEventListener('click', () => {
            this.close();
            this.onSubmit(Array.from(this.selectedFiles));
        });

        this.addStyles();
    }

    // 更新识别链接按钮状态
    updateDiscoverButton() {
        if (!this.discoverBtnEl) return;
        if (this.selectedFiles.size === 0) {
            this.discoverBtnEl.disabled = true;
            this.discoverBtnEl.style.opacity = '0.5';
            this.discoverBtnEl.style.cursor = 'not-allowed';
        } else {
            this.discoverBtnEl.disabled = false;
            this.discoverBtnEl.style.opacity = '1';
            this.discoverBtnEl.style.cursor = 'pointer';
        }
    }

    // 处理识别链接
    async handleDiscoverLinks() {
        if (this.selectedFiles.size === 0) return;

        this.discoverBtnEl!.textContent = '识别中...';
        this.discoverBtnEl!.disabled = true;

        const discoveredFiles = await this.autoDiscoverLinkedFiles();

        this.discoverBtnEl!.textContent = '识别链接';
        this.discoverBtnEl!.disabled = false;
        this.updateDiscoverButton();

        if (discoveredFiles.length === 0) {
            new Notice('没有发现新的链接文件');
            return;
        }

        // 打开确认弹窗
        new LinkedFilesConfirmModal(this.app, discoveredFiles, (confirmedFiles) => {
            if (confirmedFiles.length > 0) {
                confirmedFiles.forEach(f => this.selectedFiles.add(f));
                this.updateSelectedList();
                this.renderFileList();
                this.updateDiscoverButton();
                new Notice(`已添加 ${confirmedFiles.length} 个链接的文件`);
            }
        }).open();
    }

    // 自动发现并添加链接的 Markdown 文件
    async autoDiscoverLinkedFiles(): Promise<TFile[]> {
        const discoveredFiles = new Set<TFile>();
        const processedFiles = new Set<string>();
        const selectedFilesArray = Array.from(this.selectedFiles);

        const processFile = async (file: TFile) => {
            if (processedFiles.has(file.path)) return;
            processedFiles.add(file.path);

            try {
                const content = await this.app.vault.read(file);
                
                // 1. 匹配 Obsidian 内部链接：[[文件名]] 或 [[文件名|显示文本]]
                const wikiLinkRegex = /\[\[([^\]|]+)(?:\|[^\]]*)?\]\]/g;
                let match;

                while ((match = wikiLinkRegex.exec(content)) !== null) {
                    const linkPath = match[1]?.trim();
                    if (!linkPath) continue;

                    // 处理链接路径，移除锚点 (#heading)
                    const cleanLinkPath = linkPath.split('#')[0];
                    if (!cleanLinkPath) continue;

                    // 解码 URL 编码的路径（如 %20 转换为空格）
                    const decodedLinkPath = decodeURIComponent(cleanLinkPath);

                    // 尝试查找对应的文件
                    const targetFile = this.app.metadataCache.getFirstLinkpathDest(decodedLinkPath, file.path);

                    if (targetFile && targetFile.extension === 'md') {
                        // 检查是否已经在选择列表中
                        const alreadySelected = selectedFilesArray.some(f => f.path === targetFile.path);
                        const alreadyDiscovered = Array.from(discoveredFiles).some(f => f.path === targetFile.path);
                        if (!alreadySelected && !alreadyDiscovered) {
                            discoveredFiles.add(targetFile);
                        }
                        // 递归处理链接的文件
                        await processFile(targetFile);
                    }
                }

                // 2. 匹配 Markdown 标准链接：[显示文本](文件路径)
                const mdLinkRegex = /\[([^\]]+)\]\(([^)]+)\)/g;
                while ((match = mdLinkRegex.exec(content)) !== null) {
                    const linkPath = match[2]?.trim();
                    if (!linkPath) continue;

                    // 跳过外部链接 (http/https)
                    if (linkPath.startsWith('http://') || linkPath.startsWith('https://')) continue;

                    // 处理链接路径，移除锚点 (#heading)
                    const cleanLinkPath = linkPath.split('#')[0];
                    if (!cleanLinkPath) continue;

                    // 解码 URL 编码的路径（如 %20 转换为空格）
                    const decodedLinkPath = decodeURIComponent(cleanLinkPath);

                    // 尝试查找对应的文件
                    const targetFile = this.app.metadataCache.getFirstLinkpathDest(decodedLinkPath, file.path);

                    if (targetFile && targetFile.extension === 'md') {
                        // 检查是否已经在选择列表中
                        const alreadySelected = selectedFilesArray.some(f => f.path === targetFile.path);
                        const alreadyDiscovered = Array.from(discoveredFiles).some(f => f.path === targetFile.path);
                        if (!alreadySelected && !alreadyDiscovered) {
                            discoveredFiles.add(targetFile);
                        }
                        // 递归处理链接的文件
                        await processFile(targetFile);
                    }
                }
            } catch (e) {
                console.error('处理文件失败:', file.path, e);
            }
        };

        // 处理所有已选文件
        for (const file of selectedFilesArray) {
            await processFile(file);
        }

        return Array.from(discoveredFiles);
    }
    
    renderFileList() {
        this.fileListContainer.empty();
        this.files.forEach(file => {
            const item = this.fileListContainer.createDiv({ cls: 'file-selector-item' });
            const isSelected = Array.from(this.selectedFiles).some(f => f.path === file.path);
            
            const checkbox = item.createEl('input', {
                type: 'checkbox',
                cls: 'file-selector-checkbox'
            }) as HTMLInputElement;
            checkbox.checked = isSelected;
            
            const infoContainer = item.createDiv({ cls: 'file-selector-info' });
            infoContainer.createEl('div', { text: file.basename, cls: 'file-selector-name' });
            infoContainer.createEl('div', { text: file.path, cls: 'file-selector-path' });
            
            // 点击整行切换选中
            item.addEventListener('click', (e) => {
                if (e.target !== checkbox) {
                    checkbox.checked = !checkbox.checked;
                }
                if (checkbox.checked) {
                    this.selectedFiles.add(file);
                } else {
                    this.selectedFiles.delete(file);
                }
                this.updateSelectedList();
            });
        });
    }
    
    updateSelectedList() {
        if (!this.selectedListEl) return;
        this.selectedListEl.empty();

        // 更新标题
        const titleEl = this.contentEl.querySelector('.selected-title');
        if (titleEl) {
            titleEl.textContent = `已选择 (${this.selectedFiles.size})`;
        }

        // 更新识别链接按钮状态
        this.updateDiscoverButton();

        if (this.selectedFiles.size === 0) {
            this.selectedListEl.createEl('div', {
                text: '暂未选择文件',
                cls: 'file-selector-empty'
            });
            return;
        }

        Array.from(this.selectedFiles).forEach(file => {
            const item = this.selectedListEl.createDiv({ cls: 'file-selected-item' });
            item.createEl('span', { text: file.basename, cls: 'file-selected-name' });
            const removeBtn = item.createEl('span', { text: '×', cls: 'file-selected-remove' });
            removeBtn.addEventListener('click', () => {
                this.selectedFiles.delete(file);
                this.updateSelectedList();
                this.updateCheckboxState(file, false);
            });
        });
    }
    
    updateCheckboxState(file: TFile, checked: boolean) {
        const items = this.fileListContainer.querySelectorAll('.file-selector-item');
        items.forEach((item, index) => {
            if (this.files[index] === file) {
                const checkbox = item.querySelector('input[type="checkbox"]') as HTMLInputElement;
                if (checkbox) checkbox.checked = checked;
            }
        });
    }
    
    filterFiles(query: string) {
        const items = this.fileListContainer.querySelectorAll('.file-selector-item');
        items.forEach((item, index) => {
            const file = this.files[index];
            if (!file) return;
            const match = file.basename.toLowerCase().includes(query.toLowerCase()) ||
                         file.path.toLowerCase().includes(query.toLowerCase());
            (item as HTMLElement).style.display = match ? 'flex' : 'none';
        });
    }
    
    addStyles() {
        const style = document.createElement('style');
        style.textContent = `
            .modal-container:has(.file-selector-modal) .modal {
                width: 320px !important;
                max-width: 320px !important;
                height: 520px !important;
                max-height: 85vh !important;
            }
            .file-selector-modal {
                width: 100% !important;
                height: 100% !important;
            }
            .file-selector-modal .modal-content {
                padding: 12px;
                display: flex;
                flex-direction: column;
                height: 100%;
            }
            .file-selector-title {
                margin: 0 0 10px 0;
                font-size: 14px;
                font-weight: 600;
            }
            .file-selector-section-title {
                font-size: 11px;
                color: var(--text-muted);
                margin: 8px 0 4px 0;
                text-transform: uppercase;
                letter-spacing: 0.5px;
            }
            .file-selector-search {
                margin-bottom: 8px;
            }
            .file-selector-search input {
                width: 100%;
                padding: 6px 10px;
                border: 1px solid var(--background-modifier-border);
                border-radius: 6px;
                background: var(--background-primary);
                color: var(--text-normal);
                font-size: 12px;
            }
            .file-selector-list {
                height: 195px;
                overflow-y: scroll;
                background: var(--background-secondary);
                border-radius: 6px;
                padding: 4px;
                flex-shrink: 0;
                scrollbar-width: none;
                -ms-overflow-style: none;
            }
            .file-selector-list::-webkit-scrollbar {
                display: none;
            }
            .file-selector-item {
                display: flex;
                align-items: center;
                padding: 5px 6px;
                border-radius: 4px;
                cursor: pointer;
            }
            .file-selector-item:hover {
                background: var(--background-modifier-hover);
            }
            .file-selector-checkbox {
                margin-right: 8px;
                width: 14px;
                height: 14px;
                flex-shrink: 0;
            }
            .file-selector-info {
                flex: 1;
                min-width: 0;
                overflow: hidden;
            }
            .file-selector-name {
                font-size: 12px;
                font-weight: 500;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
            }
            .file-selector-path {
                font-size: 10px;
                color: var(--text-muted);
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
            }
            .file-selector-selected-list {
                height: 110px;
                overflow-y: scroll;
                background: var(--background-secondary);
                border-radius: 6px;
                padding: 6px;
                flex-shrink: 0;
                scrollbar-width: none;
                -ms-overflow-style: none;
            }
            .file-selector-selected-list::-webkit-scrollbar {
                display: none;
            }
            .file-selector-empty {
                font-size: 11px;
                color: var(--text-muted);
                text-align: center;
                padding: 20px 0;
            }
            .file-selected-item {
                display: flex;
                align-items: center;
                justify-content: space-between;
                padding: 4px 8px;
                background: var(--background-primary);
                border-radius: 4px;
                margin-bottom: 4px;
                font-size: 12px;
            }
            .file-selected-name {
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
                flex: 1;
            }
            .file-selected-remove {
                width: 18px;
                height: 18px;
                border-radius: 50%;
                background: var(--background-secondary);
                color: var(--text-muted);
                display: flex;
                align-items: center;
                justify-content: center;
                cursor: pointer;
                font-size: 14px;
                margin-left: 6px;
                flex-shrink: 0;
            }
            .file-selected-remove:hover {
                background: var(--text-error);
                color: white;
            }
            .file-selector-buttons {
                display: flex;
                justify-content: flex-end;
                gap: 8px;
                margin-top: 10px;
                padding-top: 10px;
                border-top: 1px solid var(--background-modifier-border);
                flex-shrink: 0;
            }
            .file-selector-buttons .export-btn {
                padding: 5px 14px;
                font-size: 12px;
            }
            .export-btn-link {
                background: var(--background-primary);
                color: var(--text-normal);
                border: 1px solid var(--background-modifier-border);
                margin-right: auto;
                display: inline-block !important;
                visibility: visible !important;
                opacity: 1 !important;
            }
            .export-btn-link:hover:not(:disabled) {
                background: var(--background-modifier-hover);
                border-color: var(--interactive-accent);
                color: var(--interactive-accent);
            }
            .export-btn-link:disabled {
                opacity: 0.5 !important;
                cursor: not-allowed;
            }
        `;
        document.head.appendChild(style);
    }
    
    onClose() {
        this.contentEl.empty();
    }
}

// 链接文件确认弹窗
class LinkedFilesConfirmModal extends Modal {
    files: TFile[];
    selectedFiles: Set<TFile> = new Set();
    onSubmit: (files: TFile[]) => void;
    addBtnEl: HTMLButtonElement | null = null;

    constructor(app: App, files: TFile[], onSubmit: (files: TFile[]) => void) {
        super(app);
        this.files = files;
        this.onSubmit = onSubmit;
        // 默认全选
        files.forEach(f => this.selectedFiles.add(f));
    }

    onOpen() {
        const { contentEl } = this;
        contentEl.addClass('linked-files-modal');

        contentEl.createEl('h3', { text: `发现 ${this.files.length} 个链接的文件`, cls: 'linked-files-title' });

        const descEl = contentEl.createEl('div', { cls: 'linked-files-desc' });
        descEl.innerHTML = '以下文件被当前选中的文件引用，可以选择一起导出。<br>点击文件可取消选择。';

        const fileListContainer = contentEl.createDiv({ cls: 'linked-files-list' });

        this.files.forEach((file, index) => {
            const item = fileListContainer.createDiv({ cls: 'linked-file-item' });
            item.dataset.index = String(index);

            const checkbox = item.createEl('input', {
                type: 'checkbox',
                cls: 'linked-file-checkbox'
            }) as HTMLInputElement;
            checkbox.checked = true;

            const infoEl = item.createDiv({ cls: 'linked-file-info' });
            infoEl.createEl('div', { text: file.basename, cls: 'linked-file-name' });
            infoEl.createEl('div', { text: file.path, cls: 'linked-file-path' });

            // 点击整行切换选中
            item.addEventListener('click', (e) => {
                if (e.target !== checkbox) {
                    checkbox.checked = !checkbox.checked;
                }
                if (checkbox.checked) {
                    this.selectedFiles.add(file);
                    item.classList.add('selected');
                } else {
                    this.selectedFiles.delete(file);
                    item.classList.remove('selected');
                }
                // 更新按钮文字
                this.updateAddButton();
            });

            item.classList.add('selected');
        });

        const buttonContainer = contentEl.createDiv({ cls: 'linked-files-buttons' });

        buttonContainer.createEl('button', {
            text: '取消',
            cls: 'export-btn export-btn-cancel'
        }).addEventListener('click', () => this.close());

        this.addBtnEl = buttonContainer.createEl('button', {
            text: `添加选中 (${this.selectedFiles.size})`,
            cls: 'export-btn export-btn-primary'
        }) as HTMLButtonElement;
        this.addBtnEl.addEventListener('click', () => {
            this.close();
            this.onSubmit(Array.from(this.selectedFiles));
        });

        this.addStyles();
    }

    // 更新添加按钮文字
    updateAddButton() {
        if (this.addBtnEl) {
            this.addBtnEl.textContent = `添加选中 (${this.selectedFiles.size})`;
        }
    }

    addStyles() {
        const style = document.createElement('style');
        style.textContent = `
            .modal-container:has(.linked-files-modal) .modal {
                width: 400px !important;
                max-width: 90vw !important;
                height: auto !important;
                max-height: 70vh !important;
            }
            .linked-files-modal {
                width: 100% !important;
            }
            .linked-files-modal .modal-content {
                padding: 20px;
                display: flex;
                flex-direction: column;
            }
            .linked-files-title {
                margin: 0 0 8px 0;
                font-size: 16px;
                font-weight: 600;
            }
            .linked-files-desc {
                font-size: 12px;
                color: var(--text-muted);
                margin-bottom: 16px;
                line-height: 1.5;
            }
            .linked-files-list {
                max-height: 300px;
                overflow-y: auto;
                background: var(--background-secondary);
                border-radius: 8px;
                padding: 8px;
                margin-bottom: 16px;
            }
            .linked-file-item {
                display: flex;
                align-items: center;
                padding: 8px 10px;
                border-radius: 6px;
                cursor: pointer;
                transition: background 0.15s;
                margin-bottom: 4px;
            }
            .linked-file-item:hover {
                background: var(--background-modifier-hover);
            }
            .linked-file-item.selected {
                background: var(--background-modifier-hover);
            }
            .linked-file-checkbox {
                margin-right: 10px;
                width: 16px;
                height: 16px;
                flex-shrink: 0;
                cursor: pointer;
            }
            .linked-file-info {
                flex: 1;
                min-width: 0;
                overflow: hidden;
            }
            .linked-file-name {
                font-size: 13px;
                font-weight: 500;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
                color: var(--text-normal);
            }
            .linked-file-path {
                font-size: 11px;
                color: var(--text-muted);
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
                margin-top: 2px;
            }
            .linked-files-buttons {
                display: flex;
                justify-content: flex-end;
                gap: 10px;
            }
        `;
        document.head.appendChild(style);
    }

    onClose() {
        this.contentEl.empty();
    }
}

// 显示所有文件的弹窗
class AllFilesModal extends Modal {
    files: TFile[];
    onSubmit: (files: TFile[]) => void;

    constructor(app: App, files: TFile[], onSubmit: (files: TFile[]) => void) {
        super(app);
        this.files = files;
        this.onSubmit = onSubmit;
    }

    onOpen() {
        const { contentEl } = this;
        contentEl.addClass('all-files-modal');
        
        contentEl.createEl('h3', { text: `已选择的文件 (${this.files.length} 个)`, cls: 'all-files-title' });
        
        const fileListContainer = contentEl.createDiv({ cls: 'all-files-list' });
        
        this.files.forEach((file, index) => {
            const item = fileListContainer.createDiv({ cls: 'all-files-item' });
            item.createEl('span', { text: file.basename, cls: 'all-files-name' });
            
            const removeBtn = item.createEl('button', { text: '×', cls: 'all-files-remove' });
            removeBtn.addEventListener('click', () => {
                this.files.splice(index, 1);
                this.onSubmit(this.files);
                this.close();
            });
        });
        
        const buttonContainer = contentEl.createDiv({ cls: 'all-files-buttons' });
        buttonContainer.createEl('button', { 
            text: '关闭', 
            cls: 'export-btn export-btn-cancel'
        }).addEventListener('click', () => this.close());
        
        this.addStyles();
    }
    
    addStyles() {
        const style = document.createElement('style');
        style.textContent = `
            .all-files-modal {
                width: 300px !important;
                max-height: 400px !important;
            }
            .all-files-modal .modal-content {
                padding: 16px;
            }
            .all-files-title {
                margin: 0 0 12px 0;
                font-size: 14px;
                font-weight: 600;
            }
            .all-files-list {
                max-height: 280px;
                overflow-y: auto;
                background: var(--background-secondary);
                border-radius: 6px;
                padding: 8px;
                margin-bottom: 12px;
            }
            .all-files-item {
                display: flex;
                justify-content: space-between;
                align-items: center;
                padding: 6px 8px;
                border-radius: 4px;
            }
            .all-files-item:hover {
                background: var(--background-modifier-hover);
            }
            .all-files-name {
                font-size: 12px;
            }
            .all-files-remove {
                background: none;
                border: none;
                color: var(--text-muted);
                cursor: pointer;
                font-size: 16px;
                padding: 0 4px;
            }
            .all-files-remove:hover {
                color: var(--text-error);
            }
            .all-files-buttons {
                display: flex;
                justify-content: flex-end;
            }
        `;
        document.head.appendChild(style);
    }
    
    onClose() {
        this.contentEl.empty();
    }
}

export class HtmlExporter {
    app: App;
    files: TFile[];
    pluginSettings: ExportHtmlSettings;

    constructor(app: App, files: TFile[], pluginSettings?: ExportHtmlSettings) {
        this.app = app;
        this.files = files;
        this.pluginSettings = pluginSettings || { excludedFolders: [] };
    }

    async export() {
        if (!this.files || this.files.length === 0) {
            new Notice("未选择文件");
            return;
        }
        new ExportSettingsModal(this.app, this.files, async (settings, files) => {
            await this.executeExport(settings, files);
        }, this.pluginSettings).open();
    }

    async executeExport(settings: ExportSettings, files: TFile[]) {
        const firstFile = files[0];
        const defaultName = firstFile ? firstFile.basename : "Wiki-Export";

        // @ts-ignore
        const result = await window.electron.remote.dialog.showSaveDialog({
            title: 'Export HTML',
            defaultPath: defaultName,
            filters: [{ name: 'HTML Files', extensions: ['html'] }]
        });

        if (result.canceled || !result.filePath) return;

        const savePath = result.filePath;
        const saveDir = path.dirname(savePath);
        const assetsDirName = 'assets';
        const assetsDirPath = path.join(saveDir, assetsDirName);
        
        let hasAttachments = false;
        let skippedFiles = 0;
        let copiedFiles = 0;

        const loadingNotice = new Notice(`正在处理...`, 0);
        
        try {
            const pagesData: PageData[] = [];
            const container = document.body.createDiv();
            container.style.display = 'none';
            
            for (const file of files) {
                const renderWrapper = container.createDiv();
                
                // === 1. 数学公式预处理：保护原始 LaTeX 代码 ===
                // 从原始内容中提取所有数学公式，使用占位符替换
                const rawContent = await this.app.vault.read(file);
                const mathFormulas: { type: 'inline' | 'block', content: string, placeholder: string }[] = [];
                let placeholderIndex = 0;
                
                // 处理块级公式 $$...$$
                let processedContent = rawContent.replace(/\$\$([\s\S]*?)\$\$/g, (match, tex) => {
                    const placeholder = `MATH_PLACEHOLDER_${placeholderIndex++}`;
                    mathFormulas.push({ type: 'block', content: tex.trim(), placeholder });
                    return placeholder;
                });
                
                // 处理行内公式 $...$
                processedContent = processedContent.replace(/(?<!\$)\$(?!\$)([^\$\n]+?)\$(?!\$)/g, (match, tex) => {
                    const placeholder = `MATH_PLACEHOLDER_${placeholderIndex++}`;
                    mathFormulas.push({ type: 'inline', content: tex.trim(), placeholder });
                    return placeholder;
                });
                
                await MarkdownRenderer.render(this.app, processedContent, renderWrapper, file.path, new Component());
                
                // === 1.5 恢复数学公式：将占位符替换回 LaTeX 代码 ===
                let html = renderWrapper.innerHTML;
                mathFormulas.forEach(({ type, content, placeholder }) => {
                    if (type === 'block') {
                        // 块级公式：用 div 包裹，方便添加样式
                        const replacement = `<div class="math-block">$$${content}$$</div>`;
                        html = html.split(placeholder).join(replacement);
                    } else {
                        // 行内公式
                        const replacement = `$${content}$`;
                        html = html.split(placeholder).join(replacement);
                    }
                });
                renderWrapper.innerHTML = html;

                // === 2. 表格处理：添加包装器使其居中 ===
                const tables = renderWrapper.querySelectorAll('table');
                tables.forEach(table => {
                    const wrapper = document.createElement('div');
                    wrapper.className = 'table-wrapper';
                    table.parentNode?.insertBefore(wrapper, table);
                    wrapper.appendChild(table);
                });

                // === 3. 上下标处理 ===
                // 先保护数学公式，避免其中的 ^ 和 ~ 被解析
                const mathRegex = /(\$\$[\s\S]*?\$\$|\$[^\$\n]+?\$)/g;
                const mathPlaceholders: string[] = [];
                
                const textNodes = renderWrapper.querySelectorAll('p, li, span, h1, h2, h3, h4, h5, h6');
                textNodes.forEach(node => {
                    if (node.nodeType === 3) return; // 跳过纯文本节点
                    
                    let text = node.innerHTML;
                    
                    // 保护数学公式：替换为占位符
                    mathPlaceholders.length = 0;
                    text = text.replace(mathRegex, (match) => {
                        mathPlaceholders.push(match);
                        return `MATH_PROTECT_${mathPlaceholders.length - 1}`;
                    });
                    
                    // 处理下标：~内容~
                    text = text.replace(/~([^~]+)~/g, '<sub>$1</sub>');
                    
                    // 处理上标：^内容^
                    text = text.replace(/\^([^^]+)\^/g, '<sup>$1</sup>');
                    
                    // 恢复数学公式
                    mathPlaceholders.forEach((formula, index) => {
                        text = text.replace(`MATH_PROTECT_${index}`, formula);
                    });
                    
                    node.innerHTML = text;
                });

                // === 4. 代码块：Notion 风格结构化 ===
                const codeBlocks = renderWrapper.querySelectorAll('pre > code');
                const commonLangs = ['Text', 'JavaScript', 'TypeScript', 'Python', 'Java', 'C', 'C++', 'C#', 'Go', 'Rust', 'PHP', 'SQL', 'HTML', 'CSS', 'Bash', 'JSON', 'YAML', 'Markdown', 'Dart', 'Swift', 'Kotlin'];

                codeBlocks.forEach(codeEl => {
                    const preEl = codeEl.parentElement as HTMLElement;
                    if (!preEl) return;

                    // A. 清理
                    preEl.querySelectorAll('button, .copy-code-button').forEach(btn => btn.remove());

                    // B. 识别语言
                    let currentLang = 'Text';
                    codeEl.classList.forEach(cls => {
                        if (cls.startsWith('language-')) {
                            let rawLang = cls.replace('language-', '');
                            currentLang = rawLang.charAt(0).toUpperCase() + rawLang.slice(1);
                            if (['cpp','csharp','sql','css','html','json'].includes(rawLang)) currentLang = rawLang.toUpperCase().replace('CPP','C++').replace('CSHARP','C#');
                        }
                    });

                    // C. 构建 DOM - 极简代码块
                    const wrapper = document.createElement('div');
                    wrapper.className = 'code-block-container';

                    // 极简头部：左侧语言选择器，右侧复制按钮
                    const header = document.createElement('div');
                    header.className = 'code-header';

                    // 左侧：语言选择器
                    const select = document.createElement('select');
                    select.className = 'lang-select';

                    const langOptions = [...commonLangs];
                    if (!langOptions.includes(currentLang)) langOptions.unshift(currentLang);

                    langOptions.forEach(lang => {
                        const option = document.createElement('option');
                        option.value = lang.toLowerCase();
                        option.text = lang;
                        if (lang === currentLang) option.selected = true;
                        select.appendChild(option);
                    });
                    header.appendChild(select);

                    // 右侧：复制按钮
                    const copyBtn = document.createElement('button');
                    copyBtn.className = 'code-copy-btn';
                    copyBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-right:4px"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>复制';
                    header.appendChild(copyBtn);

                    preEl.parentNode?.insertBefore(wrapper, preEl);
                    wrapper.appendChild(header);
                    wrapper.appendChild(preEl);
                });

                // === 5. 图片处理 ===
                const images = renderWrapper.querySelectorAll('img');
                await Promise.all(Array.from(images).map(async (img) => {
                    if (!img.src.startsWith('http')) {
                        try {
                            const response = await fetch(img.src);
                            const blob = await response.blob();
                            const base64 = await this.blobToBase64(blob);
                            if (base64) {
                                img.src = base64;
                                img.classList.add('lightbox-target');
                            }
                        } catch (e) { console.warn('Img convert fail', img.src); }
                    }
                }));

                // === 6. 附件处理 (修复大小显示) ===
                const mediaEmbeds = renderWrapper.querySelectorAll('.internal-embed');
                for (let i = 0; i < mediaEmbeds.length; i++) {
                    const embed = mediaEmbeds[i] as HTMLElement;
                    const src = embed.getAttribute('src');
                    if (!src) continue;

                    // 解码 URL 编码的路径（如 %20 转换为空格）
                    const decodedSrc = decodeURIComponent(src);
                    const targetFile = this.app.metadataCache.getFirstLinkpathDest(decodedSrc, file.path);
                    if (!targetFile) continue;

                    const ext = targetFile.extension.toLowerCase();
                    if (['png','jpg','jpeg','gif','svg','webp','bmp'].includes(ext)) continue;

                    if (!hasAttachments) {
                        if (!fs.existsSync(assetsDirPath)) fs.mkdirSync(assetsDirPath, { recursive: true });
                        hasAttachments = true;
                    }

                    const adapter = this.app.vault.adapter as FileSystemAdapter;
                    const sourcePath = adapter.getFullPath(targetFile.path);
                    const destFileName = `${targetFile.basename}.${ext}`;
                    const destPath = path.join(assetsDirPath, destFileName);
                    
                    // 【修复】正确计算文件大小
                    let fileSizeStr = "0 B";
                    let needCopy = true;

                    try {
                        const srcStat = fs.statSync(sourcePath);
                        fileSizeStr = this.formatBytes(srcStat.size); // 使用修复后的函数

                        if (fs.existsSync(destPath)) {
                            const destStat = fs.statSync(destPath);
                            if (srcStat.mtimeMs <= destStat.mtimeMs && srcStat.size === destStat.size) {
                                needCopy = false;
                                skippedFiles++;
                            }
                        }
                        if (needCopy) {
                            fs.copyFileSync(sourcePath, destPath);
                            copiedFiles++;
                        }
                    } catch (err) { console.error("Sync fail", err); }

                    const relativePath = `./${assetsDirName}/${encodeURIComponent(destFileName)}`;
                    const newContainer = document.createElement('div');
                    newContainer.className = 'attachment-wrapper';

                    if (ext === 'pdf') {
                        newContainer.innerHTML = `
                            <div class="file-card pdf-card compact" data-src="${relativePath}">
                                <div class="file-icon">📄</div>
                                <div class="file-info">
                                    <div class="file-name">${targetFile.basename}</div>
                                    <div class="file-actions">
                                        <button class="btn-preview">预览</button>
                                        <button class="btn-open" onclick="window.open('${relativePath}', '_blank')">新窗口</button>
                                        <a href="${relativePath}" class="btn-download" download>下载</a>
                                    </div>
                                </div>
                            </div>
                            <div class="pdf-preview-container" style="display:none;"></div>
                        `;
                    } else if (['mp3', 'wav', 'm4a', 'ogg', 'flac'].includes(ext)) {
                        newContainer.innerHTML = `
                            <div class="media-container audio">
                                <audio controls src="${relativePath}"></audio>
                                <div class="media-caption">🎵 ${targetFile.basename}</div>
                            </div>`;
                    } else if (['mp4', 'webm', 'mov', 'mkv'].includes(ext)) {
                        newContainer.innerHTML = `
                            <div class="media-container video">
                                <video controls src="${relativePath}"></video>
                                <div class="media-caption">🎬 ${targetFile.basename}</div>
                            </div>`;
                    } else {
                        let icon = '📄';
                        if(['zip','rar','7z'].includes(ext)) icon = '📦';
                        if(['doc','docx'].includes(ext)) icon = '📝';
                        if(['xls','xlsx','csv'].includes(ext)) icon = '📊';
                        if(['ppt','pptx'].includes(ext)) icon = '📽️';
                        if(['js','py','html','css','java','cpp','c','php','json','xml','yaml'].includes(ext)) icon = '💻';

                        newContainer.innerHTML = `
                            <a href="${relativePath}" class="file-card compact" download>
                                <div class="file-icon">${icon}</div>
                                <div class="file-info">
                                    <div class="file-name">${targetFile.basename}</div>
                                    <div class="file-meta">${ext.toUpperCase()} 文件 • ${fileSizeStr}</div>
                                </div>
                                <div class="file-download-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                                </div>
                            </a>`;
                    }
                    embed.replaceWith(newContainer);
                }

                // 链接 & TOC
                renderWrapper.querySelectorAll('a.internal-link').forEach(node => {
                    const link = node as HTMLElement;
                    const href = link.getAttribute('href');
                    // 解码 URL 编码的路径（如 %20 转换为空格）
                    const decodedHref = href ? decodeURIComponent(href) : "";
                    const target = this.app.metadataCache.getFirstLinkpathDest(decodedHref, file.path);
                    const targetIndex = files.findIndex(f => f === target);
                    if (targetIndex !== -1 && target) {
                        // 目标文件在导出列表中，使用页面内导航
                        link.removeAttribute('href');
                        link.setAttribute('onclick', `app.loadPage(${targetIndex}); return false;`);
                        link.style.cursor = 'pointer';
                        link.classList.add('wiki-link');
                        link.title = `跳转到: ${target.basename}`;
                    } else {
                        // 目标文件不在导出列表中，转换为普通文本
                        const span = document.createElement('span');
                        span.innerText = link.textContent || href || "";
                        span.style.opacity = "0.6";
                        link.replaceWith(span);
                    }
                });

                const headers = Array.from(renderWrapper.querySelectorAll('h1, h2, h3, h4, h5, h6')).map((h, index) => {
                    if (!h.id) h.id = `heading-${index}-${Date.now()}`;
                    return {
                        text: h.textContent || "Untitled",
                        level: parseInt(h.tagName.substring(1)),
                        id: h.id
                    };
                });

                pagesData.push({ title: file.basename, content: renderWrapper.innerHTML, toc: headers });
            }
            container.remove();

            const htmlContent = getTemplate(pagesData, defaultName, settings);
            fs.writeFileSync(savePath, htmlContent);
            
            loadingNotice.hide();
            
            let msg = `导出成功`;
            if (hasAttachments) msg += `\n附件: 新增 ${copiedFiles}, 跳过 ${skippedFiles}`;
            new Notice(msg, 4000);

        } catch (e) {
            console.error(e);
            loadingNotice.hide();
            new Notice('导出失败');
        }
    }

    blobToBase64(blob: Blob): Promise<string> {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });
    }

    // 【修复】正确的文件大小格式化算法
    formatBytes(bytes: number, decimals = 1) {
        if (bytes === 0) return '0 B';
        const k = 1024;
        const dm = decimals < 0 ? 0 : decimals;
        // 数组必须从 B 开始，对应 1024^0
        const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
    }
}
