// src/exporter.ts
import { App, TFile, MarkdownRenderer, Component, Notice, FileSystemAdapter, Modal, Setting } from 'obsidian';
import { getTemplate, PageData } from './template';
import * as fs from 'fs';
import * as path from 'path';

interface ExportSettings {
    pageWidth: number;
    enableToc: boolean;
    tocPosition: 'right' | 'left';
    showTitle: boolean;
    showFooter: boolean;
    footerText: string;
}

// 默认设置
const DEFAULT_SETTINGS: ExportSettings = {
    pageWidth: 960,
    enableToc: true,
    tocPosition: 'right',
    showTitle: true,
    showFooter: true,
    footerText: 'Generated by Export HTML'
};

// 存储的键名
const STORAGE_KEY = 'export-html-settings';

class ExportSettingsModal extends Modal {
    settings: ExportSettings;
    files: TFile[];
    onSubmit: (settings: ExportSettings, files: TFile[]) => void;
    previewEl: HTMLElement;
    paperEl: HTMLElement;
    fileBarEl: HTMLElement;
    exportBtnEl: HTMLButtonElement;
    footerTextAreaEl: HTMLTextAreaElement | null = null;

    constructor(app: App, files: TFile[], onSubmit: (settings: ExportSettings, files: TFile[]) => void) {
        super(app);
        this.files = files;
        this.onSubmit = onSubmit;
        // 从 localStorage 加载设置
        this.settings = this.loadSettings();
    }

    // 从 localStorage 加载设置
    loadSettings(): ExportSettings {
        try {
            const saved = localStorage.getItem(STORAGE_KEY);
            if (saved) {
                return { ...DEFAULT_SETTINGS, ...JSON.parse(saved) };
            }
        } catch (e) {
            console.error('加载设置失败:', e);
        }
        return { ...DEFAULT_SETTINGS };
    }

    // 保存设置到 localStorage
    saveSettings() {
        try {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(this.settings));
        } catch (e) {
            console.error('保存设置失败:', e);
        }
    }

    onOpen() {
        const { contentEl } = this;
        contentEl.addClass('export-settings-modal');
        
        // 主容器 - 左右布局
        const mainContainer = contentEl.createDiv({ cls: 'export-main-container' });
        
        // 左侧设置区域
        const leftPanel = mainContainer.createDiv({ cls: 'export-left-panel' });
        
        // 1. 页面宽度设置
        new Setting(leftPanel)
            .setName('页面宽度')
            .setDesc('设置内容区域宽度（像素）')
            .addText(t => t.setValue(String(this.settings.pageWidth))
                .onChange(v => {
                    this.settings.pageWidth = parseInt(v) || 960;
                    this.updatePaperSize();
                }));
        
        // 2. 目录设置
        new Setting(leftPanel)
            .setName('启用目录导航')
            .addToggle(t => t.setValue(this.settings.enableToc)
                .onChange(v => {
                    this.settings.enableToc = v;
                    this.updatePreviewContent();
                }));
        
        new Setting(leftPanel)
            .setName('目录位置')
            .addDropdown(d => d
                .addOption('right', '右侧')
                .addOption('left', '左侧')
                .setValue(this.settings.tocPosition)
                .onChange(v => {
                    this.settings.tocPosition = v as 'right' | 'left';
                    this.updatePreviewContent();
                }));
        
        // 3. 标题设置
        new Setting(leftPanel)
            .setName('显示标题')
            .addToggle(t => t.setValue(this.settings.showTitle)
                .onChange(v => {
                    this.settings.showTitle = v;
                    this.updatePreviewContent();
                }));
        
        // 4. 页脚设置
        new Setting(leftPanel)
            .setName('显示页脚')
            .addToggle(t => t.setValue(this.settings.showFooter)
                .onChange(v => {
                    this.settings.showFooter = v;
                    this.updatePreviewContent();
                }));
        
        new Setting(leftPanel)
            .setName('页脚文本')
            .setClass('export-footer-text-setting')
            .addTextArea(t => {
                t.setValue(this.settings.footerText)
                    .onChange(v => {
                        this.settings.footerText = v;
                        this.updatePreviewContent();
                    });
                t.inputEl.style.width = '100%';
                t.inputEl.style.minHeight = '60px';
                t.inputEl.style.resize = 'vertical';
                t.inputEl.rows = 2;
                // 保存 textarea 引用，用于记录高度
                this.footerTextAreaEl = t.inputEl;
                // 如果有保存的高度，应用它
                const savedHeight = localStorage.getItem('export-html-footer-height');
                if (savedHeight) {
                    t.inputEl.style.height = savedHeight;
                }
                // 监听高度变化并保存
                t.inputEl.addEventListener('mouseup', () => {
                    if (t.inputEl.style.height) {
                        localStorage.setItem('export-html-footer-height', t.inputEl.style.height);
                    }
                });
            });
        
        // 右侧预览区域
        const rightPanel = mainContainer.createDiv({ cls: 'export-right-panel' });
        rightPanel.createEl('h3', { text: '预览', cls: 'export-section-title' });
        
        // 预览容器（灰色背景）
        this.previewEl = rightPanel.createDiv({ cls: 'export-preview-container' });
        
        // 可拖动的白纸
        this.paperEl = this.previewEl.createDiv({ cls: 'export-preview-paper' });
        this.updatePreviewContent();
        
        // 初始化白纸大小
        this.updatePaperSize();
        
        // 文件选择栏（在预览下方）
        this.fileBarEl = rightPanel.createDiv({ cls: 'export-file-bar' });
        this.updateFileBar();
        
        // 底部按钮区域
        const buttonContainer = contentEl.createDiv({ cls: 'export-button-container' });
        
        buttonContainer.createEl('button', { 
            text: '取消', 
            cls: 'export-btn export-btn-cancel'
        }).addEventListener('click', () => this.close());
        
        this.exportBtnEl = buttonContainer.createEl('button', {
            text: `导出`,
            cls: 'export-btn export-btn-primary'
        }) as HTMLButtonElement;
        this.exportBtnEl.addEventListener('click', () => {
            if (this.files.length === 0) {
                new Notice('请先添加文件');
                return;
            }
            // 保存设置
            this.saveSettings();
            this.close();
            this.onSubmit(this.settings, this.files);
        });
        this.updateExportButton();
        
        // 添加样式
        this.addStyles();
    }
    
    updatePaperSize() {
        if (!this.paperEl) return;
        const width = Math.min(this.settings.pageWidth, 500); // 最大500px
        this.paperEl.style.width = width + 'px';
    }
    
    updatePreviewContent() {
        if (!this.paperEl) return;
        const tocText = this.settings.enableToc
            ? (this.settings.tocPosition === 'right' ? '右侧' : '左侧')
            : '已禁用';
        this.paperEl.innerHTML = `
            <div class="paper-content">
                ${this.settings.showTitle ? '<h1>示例文档标题</h1>' : ''}
                <p>这是预览界面展示。这是一段示例文本，用于展示导出后的页面效果。你可以通过左侧的设置面板调整各项参数，实时预览导出后的HTML页面样式。</p>
                <p>页面宽度、目录位置、标题显示和页脚设置都可以自定义。当内容较多时，白色纸张区域可以独立滚动查看。</p>
                <div class="paper-settings">
                    <strong>当前设置</strong>
                    <div>页面宽度: ${this.settings.pageWidth}px</div>
                    <div>目录: ${tocText}</div>
                    <div>标题: ${this.settings.showTitle ? '显示' : '隐藏'}</div>
                    <div>页脚: ${this.settings.showFooter ? '显示' : '隐藏'}</div>
                </div>
                ${this.settings.showFooter ? `<div class="paper-footer">${this.settings.footerText}</div>` : ''}
            </div>
        `;
    }
    
    updateFileBar() {
        if (!this.fileBarEl) return;
        
        let html = '<div class="file-bar-scroll-container">';
        
        if (this.files.length === 0) {
            html += '<span class="file-bar-empty">暂无文件，点击右侧 + 添加</span>';
        } else {
            this.files.forEach((file, index) => {
                // 获取从仓库根目录开始的路径（不包含仓库名）
                const displayPath = file.path;
                html += `
                    <span class="file-bar-item" title="${displayPath}">
                        <span class="file-bar-name">${file.basename}</span>
                        <span class="file-bar-remove" data-index="${index}" title="移除">×</span>
                    </span>
                `;
            });
        }
        
        html += '</div>';
        html += `<button class="file-bar-add-btn" title="添加文件">+</button>`;
        
        this.fileBarEl.innerHTML = html;
        
        // 绑定添加按钮事件
        const addBtn = this.fileBarEl.querySelector('.file-bar-add-btn');
        if (addBtn) {
            addBtn.addEventListener('click', () => this.openFileSelector());
        }
        
        // 绑定删除按钮事件
        const removeBtns = this.fileBarEl.querySelectorAll('.file-bar-remove');
        removeBtns.forEach(btn => {
            btn.addEventListener('click', (e) => {
                e.stopPropagation();
                const index = parseInt((btn as HTMLElement).dataset.index || '0');
                this.files.splice(index, 1);
                this.updateFileBar();
                this.updateExportButton();
            });
        });
    }
    
    showAllFiles() {
        // 显示所有文件的弹窗
        new AllFilesModal(this.app, this.files, (newFiles) => {
            this.files = newFiles;
            this.updateFileBar();
            this.updateExportButton();
        }).open();
    }
    
    updateExportButton() {
        if (!this.exportBtnEl) return;
        
        if (this.files.length === 0) {
            this.exportBtnEl.textContent = '导出';
            this.exportBtnEl.disabled = true;
            this.exportBtnEl.style.opacity = '0.5';
            this.exportBtnEl.style.cursor = 'not-allowed';
        } else {
            this.exportBtnEl.textContent = `导出 (${this.files.length} 个文件)`;
            this.exportBtnEl.disabled = false;
            this.exportBtnEl.style.opacity = '1';
            this.exportBtnEl.style.cursor = 'pointer';
        }
    }
    
    openFileSelector() {
        // 获取所有 markdown 文件
        const allFiles = this.app.vault.getFiles().filter(f => f.extension === 'md');
        
        // 打开文件选择弹窗，传入所有文件和已选文件
        new FileSelectorModal(this.app, allFiles, this.files, (selectedFiles) => {
            this.files = selectedFiles;
            this.updateFileBar();
            this.updateExportButton();
        }).open();
    }
    
    addStyles() {
        const style = document.createElement('style');
        style.setAttribute('data-export-settings', 'true');
        style.textContent = `
            /* 强制覆盖 Obsidian 默认弹窗样式 */
            .modal-container:has(.export-settings-modal) .modal {
                width: 950px !important;
                max-width: 95vw !important;
                height: 580px !important;
                max-height: 90vh !important;
            }
            .modal-container:has(.export-settings-modal) {
                align-items: center !important;
                justify-content: center !important;
            }
            .export-settings-modal {
                width: 100% !important;
                height: 100% !important;
            }
            .export-settings-modal .modal-content {
                height: 100%;
                display: flex;
                flex-direction: column;
                overflow: hidden;
                padding: 16px 20px;
            }
            .export-main-container {
                display: flex;
                flex: 1;
                gap: 16px;
                overflow: hidden;
                min-height: 0;
            }
            .export-left-panel {
                flex: 0 0 280px;
                display: flex;
                flex-direction: column;
                justify-content: flex-start;
                padding-top: 16px;
                padding-left: 12px;
                padding-right: 8px;
            }
            .export-right-panel {
                flex: 1;
                display: flex;
                flex-direction: column;
                min-width: 0;
                overflow: hidden;
            }
            .export-section-title {
                margin: 0 0 8px 0;
                font-size: 13px;
                font-weight: 600;
                color: var(--text-normal);
            }
            /* 预览容器（灰色背景） */
            .export-preview-container {
                flex: 1;
                background: var(--background-secondary);
                border-radius: 8px;
                padding: 16px;
                overflow: hidden;
                display: flex;
                align-items: flex-start;
                justify-content: center;
                min-height: 320px;
                position: relative;
            }
            /* 可拖动的白纸 */
            .export-preview-paper {
                background: var(--background-primary);
                border-radius: 4px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.1);
                min-height: 200px;
                max-height: calc(100% - 32px);
                padding: 20px;
                transition: width 0.3s ease;
                overflow-y: auto;
                position: absolute;
                top: 16px;
            }
            .paper-content h2 {
                margin: 0 0 12px 0;
                font-size: 1.3em;
            }
            .paper-content p {
                margin: 0 0 12px 0;
                line-height: 1.5;
                font-size: 0.9em;
            }
            .paper-settings {
                margin: 12px 0;
                padding: 10px;
                background: var(--background-secondary);
                border-radius: 4px;
                font-size: 0.85em;
            }
            .paper-settings strong {
                display: block;
                margin-bottom: 4px;
            }
            .paper-footer {
                margin-top: 16px;
                padding-top: 12px;
                border-top: 1px solid var(--background-modifier-border);
                text-align: center;
                color: var(--text-muted);
                font-size: 0.8em;
                white-space: pre-line;
            }
            /* 文件选择栏 */
            .export-file-bar {
                display: flex;
                align-items: center;
                gap: 8px;
                padding: 10px 12px;
                background: var(--background-secondary);
                border-radius: 6px;
                margin-top: 10px;
                min-height: 40px;
            }
            .file-bar-scroll-container {
                display: flex;
                align-items: center;
                gap: 8px;
                overflow-x: scroll;
                flex-wrap: nowrap;
                flex: 1;
                scrollbar-width: none;
                -ms-overflow-style: none;
            }
            .file-bar-scroll-container::-webkit-scrollbar {
                display: none;
            }
            .file-bar-empty {
                color: var(--text-muted);
                font-size: 12px;
                flex: 1;
            }
            .file-bar-item {
                background: var(--background-primary);
                padding: 4px 8px 4px 10px;
                border-radius: 12px;
                font-size: 12px;
                white-space: nowrap;
                border: 1px solid var(--background-modifier-border);
                display: flex;
                align-items: center;
                gap: 6px;
                position: relative;
                flex-shrink: 0;
            }
            .file-bar-name {
                max-width: 120px;
                overflow: hidden;
                text-overflow: ellipsis;
            }
            .file-bar-remove {
                width: 16px;
                height: 16px;
                border-radius: 50%;
                background: var(--background-secondary);
                color: var(--text-muted);
                display: flex;
                align-items: center;
                justify-content: center;
                cursor: pointer;
                font-size: 14px;
                line-height: 1;
                opacity: 0;
                transition: opacity 0.2s;
                flex-shrink: 0;
            }
            .file-bar-item:hover .file-bar-remove {
                opacity: 1;
            }
            .file-bar-remove:hover {
                background: var(--text-error);
                color: white;
            }
            .file-bar-add-btn {
                width: 24px;
                height: 24px;
                border-radius: 50%;
                border: 1px dashed var(--background-modifier-border);
                background: transparent;
                color: var(--text-muted);
                cursor: pointer;
                font-size: 16px;
                line-height: 1;
                display: flex;
                align-items: center;
                justify-content: center;
                flex-shrink: 0;
            }
            .file-bar-add-btn:hover {
                border-color: var(--interactive-accent);
                color: var(--interactive-accent);
            }
            .export-button-container {
                display: flex;
                justify-content: flex-end;
                gap: 12px;
                margin-top: 16px;
                padding-top: 16px;
                margin-bottom: 8px;
                border-top: 1px solid var(--background-modifier-border);
                flex-shrink: 0;
            }
            .export-btn {
                padding: 6px 20px;
                border-radius: 6px;
                border: 1px solid var(--background-modifier-border);
                cursor: pointer;
                font-size: 13px;
                transition: all 0.2s;
            }
            .export-btn-cancel {
                background: var(--background-primary);
                color: var(--text-normal);
            }
            .export-btn-cancel:hover {
                background: var(--background-modifier-hover);
            }
            .export-btn-primary {
                background: var(--interactive-accent);
                color: var(--text-on-accent);
                border-color: var(--interactive-accent);
            }
            .export-btn-primary:hover:not(:disabled) {
                background: var(--interactive-accent-hover);
            }
            .setting-item {
                padding: 6px 0;
                border-bottom: 1px solid var(--background-modifier-border-hover);
            }
            .setting-item:last-child {
                border-bottom: none;
            }
            .setting-item-name {
                font-size: 13px;
            }
            .setting-item-description {
                font-size: 11px;
                color: var(--text-muted);
            }
            /* 页脚文本输入框样式 */
            .export-footer-text-setting {
                flex-direction: column !important;
                align-items: flex-start !important;
            }
            .export-footer-text-setting .setting-item-info {
                margin-bottom: 6px;
            }
            .export-footer-text-setting .setting-item-control {
                width: 100% !important;
            }
            .export-footer-text-setting textarea {
                width: 100% !important;
                min-height: 60px !important;
                max-height: 120px !important;
                padding: 8px 10px !important;
                font-size: 12px !important;
                line-height: 1.4 !important;
                resize: vertical !important;
                border-radius: 6px !important;
                border: 1px solid var(--background-modifier-border) !important;
                background: var(--background-primary) !important;
                color: var(--text-normal) !important;
            }
            .export-footer-text-setting textarea:focus {
                border-color: var(--interactive-accent) !important;
                outline: none !important;
            }
        `;
        document.head.appendChild(style);
    }
    
    onClose() { 
        this.contentEl.empty();
        const style = document.querySelector('style[data-export-settings]');
        if (style) style.remove();
    }
}

// 文件选择弹窗（优化版）
class FileSelectorModal extends Modal {
    files: TFile[];
    selectedFiles: Set<TFile> = new Set();
    onSubmit: (files: TFile[]) => void;
    selectedListEl: HTMLElement;
    fileListContainer: HTMLElement;

    constructor(app: App, files: TFile[], alreadySelected: TFile[], onSubmit: (files: TFile[]) => void) {
        super(app);
        this.files = files;
        this.onSubmit = onSubmit;
        // 初始化已选文件
        alreadySelected.forEach(f => this.selectedFiles.add(f));
    }

    onOpen() {
        const { contentEl } = this;
        contentEl.addClass('file-selector-modal');
        
        contentEl.createEl('h3', { text: '选择文件', cls: 'file-selector-title' });
        
        // 搜索框
        const searchBox = contentEl.createDiv({ cls: 'file-selector-search' });
        const searchInput = searchBox.createEl('input', {
            type: 'text',
            placeholder: '搜索文件...'
        });
        searchInput.addEventListener('input', () => {
            this.filterFiles(searchInput.value);
        });
        
        // 上方：可选文件列表
        contentEl.createEl('div', { text: '可选文件', cls: 'file-selector-section-title' });
        this.fileListContainer = contentEl.createDiv({ cls: 'file-selector-list' });
        this.renderFileList();
        
        // 下方：已选文件列表
        contentEl.createEl('div', { text: `已选择 (${this.selectedFiles.size})`, cls: 'file-selector-section-title selected-title' });
        this.selectedListEl = contentEl.createDiv({ cls: 'file-selector-selected-list' });
        this.updateSelectedList();
        
        // 按钮
        const buttonContainer = contentEl.createDiv({ cls: 'file-selector-buttons' });
        
        buttonContainer.createEl('button', { 
            text: '取消', 
            cls: 'export-btn export-btn-cancel'
        }).addEventListener('click', () => this.close());
        
        buttonContainer.createEl('button', { 
            text: '添加', 
            cls: 'export-btn export-btn-primary'
        }).addEventListener('click', () => {
            this.close();
            this.onSubmit(Array.from(this.selectedFiles));
        });
        
        this.addStyles();
    }
    
    renderFileList() {
        this.fileListContainer.empty();
        this.files.forEach(file => {
            const item = this.fileListContainer.createDiv({ cls: 'file-selector-item' });
            const isSelected = Array.from(this.selectedFiles).some(f => f.path === file.path);
            
            const checkbox = item.createEl('input', {
                type: 'checkbox',
                cls: 'file-selector-checkbox'
            }) as HTMLInputElement;
            checkbox.checked = isSelected;
            
            const infoContainer = item.createDiv({ cls: 'file-selector-info' });
            infoContainer.createEl('div', { text: file.basename, cls: 'file-selector-name' });
            infoContainer.createEl('div', { text: file.path, cls: 'file-selector-path' });
            
            // 点击整行切换选中
            item.addEventListener('click', (e) => {
                if (e.target !== checkbox) {
                    checkbox.checked = !checkbox.checked;
                }
                if (checkbox.checked) {
                    this.selectedFiles.add(file);
                } else {
                    this.selectedFiles.delete(file);
                }
                this.updateSelectedList();
            });
        });
    }
    
    updateSelectedList() {
        if (!this.selectedListEl) return;
        this.selectedListEl.empty();
        
        // 更新标题
        const titleEl = this.contentEl.querySelector('.selected-title');
        if (titleEl) {
            titleEl.textContent = `已选择 (${this.selectedFiles.size})`;
        }
        
        if (this.selectedFiles.size === 0) {
            this.selectedListEl.createEl('div', { 
                text: '暂未选择文件', 
                cls: 'file-selector-empty' 
            });
            return;
        }
        
        Array.from(this.selectedFiles).forEach(file => {
            const item = this.selectedListEl.createDiv({ cls: 'file-selected-item' });
            item.createEl('span', { text: file.basename, cls: 'file-selected-name' });
            const removeBtn = item.createEl('span', { text: '×', cls: 'file-selected-remove' });
            removeBtn.addEventListener('click', () => {
                this.selectedFiles.delete(file);
                this.updateSelectedList();
                this.updateCheckboxState(file, false);
            });
        });
    }
    
    updateCheckboxState(file: TFile, checked: boolean) {
        const items = this.fileListContainer.querySelectorAll('.file-selector-item');
        items.forEach((item, index) => {
            if (this.files[index] === file) {
                const checkbox = item.querySelector('input[type="checkbox"]') as HTMLInputElement;
                if (checkbox) checkbox.checked = checked;
            }
        });
    }
    
    filterFiles(query: string) {
        const items = this.fileListContainer.querySelectorAll('.file-selector-item');
        items.forEach((item, index) => {
            const file = this.files[index];
            if (!file) return;
            const match = file.basename.toLowerCase().includes(query.toLowerCase()) ||
                         file.path.toLowerCase().includes(query.toLowerCase());
            (item as HTMLElement).style.display = match ? 'flex' : 'none';
        });
    }
    
    addStyles() {
        const style = document.createElement('style');
        style.textContent = `
            .modal-container:has(.file-selector-modal) .modal {
                width: 320px !important;
                max-width: 320px !important;
                height: 520px !important;
                max-height: 85vh !important;
            }
            .file-selector-modal {
                width: 100% !important;
                height: 100% !important;
            }
            .file-selector-modal .modal-content {
                padding: 12px;
                display: flex;
                flex-direction: column;
                height: 100%;
            }
            .file-selector-title {
                margin: 0 0 10px 0;
                font-size: 14px;
                font-weight: 600;
            }
            .file-selector-section-title {
                font-size: 11px;
                color: var(--text-muted);
                margin: 8px 0 4px 0;
                text-transform: uppercase;
                letter-spacing: 0.5px;
            }
            .file-selector-search {
                margin-bottom: 8px;
            }
            .file-selector-search input {
                width: 100%;
                padding: 6px 10px;
                border: 1px solid var(--background-modifier-border);
                border-radius: 6px;
                background: var(--background-primary);
                color: var(--text-normal);
                font-size: 12px;
            }
            .file-selector-list {
                height: 195px;
                overflow-y: scroll;
                background: var(--background-secondary);
                border-radius: 6px;
                padding: 4px;
                flex-shrink: 0;
                scrollbar-width: none;
                -ms-overflow-style: none;
            }
            .file-selector-list::-webkit-scrollbar {
                display: none;
            }
            .file-selector-item {
                display: flex;
                align-items: center;
                padding: 5px 6px;
                border-radius: 4px;
                cursor: pointer;
            }
            .file-selector-item:hover {
                background: var(--background-modifier-hover);
            }
            .file-selector-checkbox {
                margin-right: 8px;
                width: 14px;
                height: 14px;
                flex-shrink: 0;
            }
            .file-selector-info {
                flex: 1;
                min-width: 0;
                overflow: hidden;
            }
            .file-selector-name {
                font-size: 12px;
                font-weight: 500;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
            }
            .file-selector-path {
                font-size: 10px;
                color: var(--text-muted);
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
            }
            .file-selector-selected-list {
                height: 110px;
                overflow-y: scroll;
                background: var(--background-secondary);
                border-radius: 6px;
                padding: 6px;
                flex-shrink: 0;
                scrollbar-width: none;
                -ms-overflow-style: none;
            }
            .file-selector-selected-list::-webkit-scrollbar {
                display: none;
            }
            .file-selector-empty {
                font-size: 11px;
                color: var(--text-muted);
                text-align: center;
                padding: 20px 0;
            }
            .file-selected-item {
                display: flex;
                align-items: center;
                justify-content: space-between;
                padding: 4px 8px;
                background: var(--background-primary);
                border-radius: 4px;
                margin-bottom: 4px;
                font-size: 12px;
            }
            .file-selected-name {
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
                flex: 1;
            }
            .file-selected-remove {
                width: 18px;
                height: 18px;
                border-radius: 50%;
                background: var(--background-secondary);
                color: var(--text-muted);
                display: flex;
                align-items: center;
                justify-content: center;
                cursor: pointer;
                font-size: 14px;
                margin-left: 6px;
                flex-shrink: 0;
            }
            .file-selected-remove:hover {
                background: var(--text-error);
                color: white;
            }
            .file-selector-buttons {
                display: flex;
                justify-content: flex-end;
                gap: 8px;
                margin-top: 10px;
                padding-top: 10px;
                border-top: 1px solid var(--background-modifier-border);
                flex-shrink: 0;
            }
            .file-selector-buttons .export-btn {
                padding: 5px 14px;
                font-size: 12px;
            }
        `;
        document.head.appendChild(style);
    }
    
    onClose() {
        this.contentEl.empty();
    }
}

// 显示所有文件的弹窗
class AllFilesModal extends Modal {
    files: TFile[];
    onSubmit: (files: TFile[]) => void;

    constructor(app: App, files: TFile[], onSubmit: (files: TFile[]) => void) {
        super(app);
        this.files = files;
        this.onSubmit = onSubmit;
    }

    onOpen() {
        const { contentEl } = this;
        contentEl.addClass('all-files-modal');
        
        contentEl.createEl('h3', { text: `已选择的文件 (${this.files.length} 个)`, cls: 'all-files-title' });
        
        const fileListContainer = contentEl.createDiv({ cls: 'all-files-list' });
        
        this.files.forEach((file, index) => {
            const item = fileListContainer.createDiv({ cls: 'all-files-item' });
            item.createEl('span', { text: file.basename, cls: 'all-files-name' });
            
            const removeBtn = item.createEl('button', { text: '×', cls: 'all-files-remove' });
            removeBtn.addEventListener('click', () => {
                this.files.splice(index, 1);
                this.onSubmit(this.files);
                this.close();
            });
        });
        
        const buttonContainer = contentEl.createDiv({ cls: 'all-files-buttons' });
        buttonContainer.createEl('button', { 
            text: '关闭', 
            cls: 'export-btn export-btn-cancel'
        }).addEventListener('click', () => this.close());
        
        this.addStyles();
    }
    
    addStyles() {
        const style = document.createElement('style');
        style.textContent = `
            .all-files-modal {
                width: 300px !important;
                max-height: 400px !important;
            }
            .all-files-modal .modal-content {
                padding: 16px;
            }
            .all-files-title {
                margin: 0 0 12px 0;
                font-size: 14px;
                font-weight: 600;
            }
            .all-files-list {
                max-height: 280px;
                overflow-y: auto;
                background: var(--background-secondary);
                border-radius: 6px;
                padding: 8px;
                margin-bottom: 12px;
            }
            .all-files-item {
                display: flex;
                justify-content: space-between;
                align-items: center;
                padding: 6px 8px;
                border-radius: 4px;
            }
            .all-files-item:hover {
                background: var(--background-modifier-hover);
            }
            .all-files-name {
                font-size: 12px;
            }
            .all-files-remove {
                background: none;
                border: none;
                color: var(--text-muted);
                cursor: pointer;
                font-size: 16px;
                padding: 0 4px;
            }
            .all-files-remove:hover {
                color: var(--text-error);
            }
            .all-files-buttons {
                display: flex;
                justify-content: flex-end;
            }
        `;
        document.head.appendChild(style);
    }
    
    onClose() {
        this.contentEl.empty();
    }
}

export class HtmlExporter {
    app: App;
    files: TFile[];

    constructor(app: App, files: TFile[]) {
        this.app = app;
        this.files = files;
    }

    async export() {
        if (!this.files || this.files.length === 0) {
            new Notice("未选择文件");
            return;
        }
        new ExportSettingsModal(this.app, this.files, async (settings, files) => {
            await this.executeExport(settings, files);
        }).open();
    }

    async executeExport(settings: ExportSettings, files: TFile[]) {
        const firstFile = files[0];
        const defaultName = firstFile ? firstFile.basename : "Wiki-Export";

        // @ts-ignore
        const result = await window.electron.remote.dialog.showSaveDialog({
            title: 'Export HTML',
            defaultPath: defaultName,
            filters: [{ name: 'HTML Files', extensions: ['html'] }]
        });

        if (result.canceled || !result.filePath) return;

        const savePath = result.filePath;
        const saveDir = path.dirname(savePath);
        const assetsDirName = 'assets';
        const assetsDirPath = path.join(saveDir, assetsDirName);
        
        let hasAttachments = false;
        let skippedFiles = 0;
        let copiedFiles = 0;

        const loadingNotice = new Notice(`正在处理...`, 0);
        
        try {
            const pagesData: PageData[] = [];
            const container = document.body.createDiv();
            container.style.display = 'none';
            
            for (const file of files) {
                const renderWrapper = container.createDiv();
                await MarkdownRenderer.render(this.app, await this.app.vault.read(file), renderWrapper, file.path, new Component());

                // === 1. 数学公式：简单还原为文本 (暂不深究渲染) ===
                const mathElements = renderWrapper.querySelectorAll('.math, mjx-container');
                mathElements.forEach(el => {
                    let tex = el.querySelector('annotation[encoding="application/x-tex"]')?.textContent 
                           || el.getAttribute('aria-label') 
                           || el.getAttribute('alttext') 
                           || '';
                    if (tex) {
                        const isBlock = el.classList.contains('math-block') || el.tagName.toLowerCase() === 'div';
                        const span = document.createElement('span');
                        span.textContent = isBlock ? `$$${tex}$$` : `$${tex}$`;
                        el.replaceWith(span);
                    }
                });

                // === 2. 表格处理：添加包装器使其居中 ===
                const tables = renderWrapper.querySelectorAll('table');
                tables.forEach(table => {
                    const wrapper = document.createElement('div');
                    wrapper.className = 'table-wrapper';
                    table.parentNode?.insertBefore(wrapper, table);
                    wrapper.appendChild(table);
                });

                // === 3. 上下标处理 ===
                const textNodes = renderWrapper.querySelectorAll('p, li, span, h1, h2, h3, h4, h5, h6');
                textNodes.forEach(node => {
                    if (node.nodeType === 3) return; // 跳过纯文本节点
                    
                    let text = node.innerHTML;
                    
                    // 处理下标：~内容~
                    text = text.replace(/~([^~]+)~/g, '<sub>$1</sub>');
                    
                    // 处理上标：^内容^
                    text = text.replace(/\^([^^]+)\^/g, '<sup>$1</sup>');
                    
                    node.innerHTML = text;
                });

                // === 4. 代码块：Notion 风格结构化 ===
                const codeBlocks = renderWrapper.querySelectorAll('pre > code');
                const commonLangs = ['Text', 'JavaScript', 'TypeScript', 'Python', 'Java', 'C', 'C++', 'C#', 'Go', 'Rust', 'PHP', 'SQL', 'HTML', 'CSS', 'Bash', 'JSON', 'YAML', 'Markdown', 'Dart', 'Swift', 'Kotlin'];

                codeBlocks.forEach(codeEl => {
                    const preEl = codeEl.parentElement as HTMLElement;
                    if (!preEl) return;

                    // A. 清理
                    preEl.querySelectorAll('button, .copy-code-button').forEach(btn => btn.remove());

                    // B. 识别语言
                    let currentLang = 'Text';
                    codeEl.classList.forEach(cls => {
                        if (cls.startsWith('language-')) {
                            let rawLang = cls.replace('language-', '');
                            currentLang = rawLang.charAt(0).toUpperCase() + rawLang.slice(1);
                            if (['cpp','csharp','sql','css','html','json'].includes(rawLang)) currentLang = rawLang.toUpperCase().replace('CPP','C++').replace('CSHARP','C#');
                        }
                    });

                    // C. 构建 DOM
                    const wrapper = document.createElement('div');
                    wrapper.className = 'code-block-container';
                    
                    const controls = document.createElement('div');
                    controls.className = 'code-controls';

                    const select = document.createElement('select');
                    select.className = 'lang-select';
                    
                    const langOptions = [...commonLangs];
                    if (!langOptions.includes(currentLang)) langOptions.unshift(currentLang);
                    
                    langOptions.forEach(lang => {
                        const option = document.createElement('option');
                        option.value = lang.toLowerCase();
                        option.text = lang;
                        if (lang === currentLang) option.selected = true;
                        select.appendChild(option);
                    });
                    controls.appendChild(select);

                    const copyBtn = document.createElement('button');
                    copyBtn.className = 'code-copy-btn';
                    copyBtn.innerHTML = '复制';
                    controls.appendChild(copyBtn);

                    preEl.parentNode?.insertBefore(wrapper, preEl);
                    wrapper.appendChild(controls);
                    wrapper.appendChild(preEl);
                });

                // === 5. 图片处理 ===
                const images = renderWrapper.querySelectorAll('img');
                await Promise.all(Array.from(images).map(async (img) => {
                    if (!img.src.startsWith('http')) {
                        try {
                            const response = await fetch(img.src);
                            const blob = await response.blob();
                            const base64 = await this.blobToBase64(blob);
                            if (base64) {
                                img.src = base64;
                                img.classList.add('lightbox-target');
                            }
                        } catch (e) { console.warn('Img convert fail', img.src); }
                    }
                }));

                // === 6. 附件处理 (修复大小显示) ===
                const mediaEmbeds = renderWrapper.querySelectorAll('.internal-embed');
                for (let i = 0; i < mediaEmbeds.length; i++) {
                    const embed = mediaEmbeds[i] as HTMLElement;
                    const src = embed.getAttribute('src');
                    if (!src) continue;

                    const targetFile = this.app.metadataCache.getFirstLinkpathDest(src, file.path);
                    if (!targetFile) continue;

                    const ext = targetFile.extension.toLowerCase();
                    if (['png','jpg','jpeg','gif','svg','webp','bmp'].includes(ext)) continue;

                    if (!hasAttachments) {
                        if (!fs.existsSync(assetsDirPath)) fs.mkdirSync(assetsDirPath, { recursive: true });
                        hasAttachments = true;
                    }

                    const adapter = this.app.vault.adapter as FileSystemAdapter;
                    const sourcePath = adapter.getFullPath(targetFile.path);
                    const destFileName = `${targetFile.basename}.${ext}`;
                    const destPath = path.join(assetsDirPath, destFileName);
                    
                    // 【修复】正确计算文件大小
                    let fileSizeStr = "0 B";
                    let needCopy = true;

                    try {
                        const srcStat = fs.statSync(sourcePath);
                        fileSizeStr = this.formatBytes(srcStat.size); // 使用修复后的函数

                        if (fs.existsSync(destPath)) {
                            const destStat = fs.statSync(destPath);
                            if (srcStat.mtimeMs <= destStat.mtimeMs && srcStat.size === destStat.size) {
                                needCopy = false;
                                skippedFiles++;
                            }
                        }
                        if (needCopy) {
                            fs.copyFileSync(sourcePath, destPath);
                            copiedFiles++;
                        }
                    } catch (err) { console.error("Sync fail", err); }

                    const relativePath = `./${assetsDirName}/${encodeURIComponent(destFileName)}`;
                    const newContainer = document.createElement('div');
                    newContainer.className = 'attachment-wrapper';

                    if (ext === 'pdf') {
                        newContainer.innerHTML = `
                            <div class="file-card pdf-card compact" data-src="${relativePath}">
                                <div class="file-icon">📄</div>
                                <div class="file-info">
                                    <div class="file-name">${targetFile.basename}</div>
                                    <div class="file-actions">
                                        <button class="btn-preview">预览</button>
                                        <button class="btn-open" onclick="window.open('${relativePath}', '_blank')">新窗口</button>
                                        <a href="${relativePath}" class="btn-download" download>下载</a>
                                    </div>
                                </div>
                            </div>
                            <div class="pdf-preview-container" style="display:none;"></div>
                        `;
                    } else if (['mp3', 'wav', 'm4a', 'ogg', 'flac'].includes(ext)) {
                        newContainer.innerHTML = `
                            <div class="media-container audio">
                                <audio controls src="${relativePath}"></audio>
                                <div class="media-caption">🎵 ${targetFile.basename}</div>
                            </div>`;
                    } else if (['mp4', 'webm', 'mov', 'mkv'].includes(ext)) {
                        newContainer.innerHTML = `
                            <div class="media-container video">
                                <video controls src="${relativePath}"></video>
                                <div class="media-caption">🎬 ${targetFile.basename}</div>
                            </div>`;
                    } else {
                        let icon = '📄';
                        if(['zip','rar','7z'].includes(ext)) icon = '📦';
                        if(['doc','docx'].includes(ext)) icon = '📝';
                        if(['xls','xlsx','csv'].includes(ext)) icon = '📊';
                        if(['ppt','pptx'].includes(ext)) icon = '📽️';
                        if(['js','py','html','css','java','cpp','c','php','json','xml','yaml'].includes(ext)) icon = '💻';

                        newContainer.innerHTML = `
                            <a href="${relativePath}" class="file-card compact" download>
                                <div class="file-icon">${icon}</div>
                                <div class="file-info">
                                    <div class="file-name">${targetFile.basename}</div>
                                    <div class="file-meta">${ext.toUpperCase()} 文件 • ${fileSizeStr}</div>
                                </div>
                                <div class="file-download-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>
                                </div>
                            </a>`;
                    }
                    embed.replaceWith(newContainer);
                }

                // 链接 & TOC
                renderWrapper.querySelectorAll('a.internal-link').forEach(node => {
                    const link = node as HTMLElement;
                    const href = link.getAttribute('href');
                    const target = this.app.metadataCache.getFirstLinkpathDest(href || "", file.path);
                    const isIncluded = files.find(f => f === target);
                    if (isIncluded && target) {
                        link.removeAttribute('href');
                        link.setAttribute('onclick', `app.navigate('${target.basename}')`);
                        link.style.cursor = 'pointer';
                    } else {
                        const span = document.createElement('span');
                        span.innerText = link.textContent || href || "";
                        span.style.opacity = "0.6";
                        link.replaceWith(span);
                    }
                });

                const headers = Array.from(renderWrapper.querySelectorAll('h1, h2, h3, h4, h5, h6')).map((h, index) => {
                    if (!h.id) h.id = `heading-${index}-${Date.now()}`;
                    return {
                        text: h.textContent || "Untitled",
                        level: parseInt(h.tagName.substring(1)),
                        id: h.id
                    };
                });

                pagesData.push({ title: file.basename, content: renderWrapper.innerHTML, toc: headers });
            }
            container.remove();

            const htmlContent = getTemplate(pagesData, defaultName, settings);
            fs.writeFileSync(savePath, htmlContent);
            
            loadingNotice.hide();
            
            let msg = `导出成功`;
            if (hasAttachments) msg += `\n附件: 新增 ${copiedFiles}, 跳过 ${skippedFiles}`;
            new Notice(msg, 4000);

        } catch (e) {
            console.error(e);
            loadingNotice.hide();
            new Notice('导出失败');
        }
    }

    blobToBase64(blob: Blob): Promise<string> {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });
    }

    // 【修复】正确的文件大小格式化算法
    formatBytes(bytes: number, decimals = 1) {
        if (bytes === 0) return '0 B';
        const k = 1024;
        const dm = decimals < 0 ? 0 : decimals;
        // 数组必须从 B 开始，对应 1024^0
        const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
    }
}
