// src/template.ts

export interface PageData {
    title: string;
    content: string;
    toc: { text: string; level: number; id: string }[];
}

export interface ExportSettings {
    pageWidth: number;
    enableToc: boolean;
    tocPosition: 'right' | 'left';
    showTitle: boolean;
    showFooter: boolean;
    footerText: string;
}

export function getTemplate(pages: PageData[], defaultTitle: string, settings: ExportSettings = { 
    pageWidth: 960,
    enableToc: true,
    tocPosition: 'right',
    showTitle: true,
    showFooter: true,
    footerText: 'Generated by Export HTML'
}) {
    const dataScript = `const WIKI_DATA = ${JSON.stringify(pages)};`;
    const isSinglePage = pages.length === 1;

    // ==========================================
    // 1. SVG 图标
    // ==========================================
    const svgSun = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>`;
    const svgMoon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:block"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>`;
    const svgMenu = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M3 4H21V6H3V4ZM3 11H21V13H3V11ZM3 18H21V20H3V18Z"></path></svg>`;
    const svgFile = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M14 2H6C4.9 2 4 2.9 4 4V20C4 21.1 4.9 22 6 22H18C19.1 22 20 21.1 20 20V8L14 2ZM18 20H6V4H13V9H18V20Z"/></svg>`;
    const svgCopy = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>`;
    const svgCheck = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>`;

    // ==========================================
    // 2. CSS 变量
    // ==========================================
    const cssVariables = `
        :root {
            --primary: #2563eb;
            --bg-body: #ffffff;
            --text-main: #37352f;
            --text-sec: #787774;
            --border: #e5e7eb;
            --sidebar-bg: #fbfbfa;
            --hover-bg: #f3f3f3; 
            --toc-line-inactive: #e0e0e0;
            --toc-line-active: #37352f;
            --popover-bg: #ffffff;
            --popover-shadow: rgba(15, 15, 15, 0.04) 0px 0px 0px 1px, rgba(15, 15, 15, 0.08) 0px 4px 12px, rgba(15, 15, 15, 0.1) 0px 12px 32px;
            --highlight-bg: rgba(37, 99, 235, 0.15);
            --card-bg: #ffffff;
            --card-border: #e0e0e0;
            --code-bg: #f9fafb; /* 极浅灰 */
            --code-header: transparent;
            --radius-md: 10px;
            
            --scroll-track: transparent;
            --scroll-thumb: #d3d1cb;
            --scroll-thumb-hover: #aeaca6;
        }
        [data-theme="dark"] {
            --primary: #60a5fa;
            --bg-body: #191919;
            --text-main: #d4d4d4;
            --text-sec: #9b9b9b;
            --border: #2f2f2f;
            --sidebar-bg: #202020;
            --hover-bg: #2c2c2c;
            --toc-line-inactive: #3f3f3f;
            --toc-line-active: #d4d4d4;
            --popover-bg: #252525;
            --popover-shadow: rgba(0, 0, 0, 0.6) 0px 0px 0px 1px, rgba(0, 0, 0, 0.7) 0px 4px 12px, rgba(0, 0, 0, 0.8) 0px 12px 32px;
            --highlight-bg: rgba(96, 165, 250, 0.2);
            --card-bg: #2a2a2a;
            --card-border: #444;
            --code-bg: #262626;
            --code-header: transparent;
            --scroll-thumb: #474747;
            --scroll-thumb-hover: #5a5a5a;
        }
        * { box-sizing: border-box; -webkit-tap-highlight-color: transparent; }
        
        ::-webkit-scrollbar { width: 8px; height: 8px; }
        ::-webkit-scrollbar-track { background: var(--scroll-track); }
        ::-webkit-scrollbar-thumb { background: var(--scroll-thumb); border-radius: 4px; }
        ::-webkit-scrollbar-thumb:hover { background: var(--scroll-thumb-hover); }
    `;

    const cssLayout = `
        body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; background: var(--bg-body); color: var(--text-main); height: 100vh; display: flex; overflow: hidden; transition: background 0.3s, color 0.3s; }
        .layout-container { display: flex; width: 100%; height: 100%; position: relative; }

        #sidebar { width: 260px; background: var(--sidebar-bg); border-right: 1px solid var(--border); display: flex; flex-direction: column; z-index: 60; flex-shrink: 0; transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1); }
        .search-box { padding: 12px; }
        .search-box input { width: 100%; padding: 6px 10px; border-radius: 4px; border: 1px solid var(--border); outline: none; background: var(--bg-body); color: var(--text-main); font-size: 14px; }
        .search-box input:focus { border-color: var(--primary); }
        .file-list { flex: 1; overflow-y: auto; padding: 6px; list-style: none; margin: 0; }
        .file-item { padding: 8px 12px; margin-bottom: 2px; border-radius: 4px; cursor: pointer; color: var(--text-sec); font-size: 14px; display: flex; align-items: center; gap: 8px; transition: background 0.1s; }
        .file-item:hover { background: var(--hover-bg); color: var(--text-main); }
        .file-item.active { background: var(--hover-bg); color: var(--text-main); font-weight: 600; }
        
        /* 文件列表收起/展开 */
        .layout-container.hide-sidebar #sidebar { transform: translateX(-100%); }
        /* 展开状态：按钮在侧边栏右侧 */
        .sidebar-toggle { position: fixed; bottom: 80px; left: 244px; width: 32px; height: 32px; border-radius: 50%; background: var(--sidebar-bg); border: 1px solid var(--border); display: flex; align-items: center; justify-content: center; cursor: pointer; z-index: 100; opacity: 1; pointer-events: auto; transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); box-shadow: 0 2px 6px rgba(0,0,0,0.1); }
        .sidebar-toggle:hover { background: var(--hover-bg); border-color: var(--primary); transform: scale(1.1); }
        /* 收起状态：按钮移动到左侧 */
        .layout-container.hide-sidebar .sidebar-toggle { left: 20px; background: var(--bg-body); }
        .sidebar-toggle svg { width: 16px; height: 16px; fill: var(--text-sec); transition: transform 0.3s; }
        /* 展开时图标旋转 */
        .layout-container:not(.hide-sidebar) .sidebar-toggle svg { transform: rotate(180deg); }

        #main-scroll { flex: 1; overflow-y: auto; overflow-x: hidden; scroll-behavior: smooth; position: relative; }
        .article-container { max-width: ${settings.pageWidth}px; margin: 0 auto; padding: 40px 120px 150px; transition: padding 0.3s; }
        
        h1.page-title { font-size: 2.4rem; font-weight: 700; margin-bottom: 1.5rem; padding-bottom: 1rem; border-bottom: 1px solid var(--border); line-height: 1.2; margin-top: 0; }
        
        h1, h2, h3, h4, h5, h6 { 
            scroll-margin-top: 0; 
            border-radius: 6px; padding: 4px 12px; margin-left: -12px; margin-right: -12px; transition: background-color 0.2s; 
        }
        .highlight-target { background-color: var(--highlight-bg); }

        a { color: var(--primary); text-decoration: none; cursor: pointer; border-bottom: 1px solid transparent; transition: border 0.2s; }
        a:hover { border-bottom-color: var(--primary); }
        
        /* Wiki 链接样式 */
        a.wiki-link {
            color: var(--primary);
            border-bottom: 1px dashed var(--primary);
            font-weight: 500;
        }
        a.wiki-link:hover {
            background: var(--highlight-bg);
            border-bottom-style: solid;
            border-radius: 3px;
            padding: 0 2px;
            margin: 0 -2px;
        }
        img { max-width: 100%; border-radius: 4px; cursor: zoom-in; display: block; margin: 1.5em auto; }
        blockquote { border-left: 3px solid var(--text-main); margin: 1.5em 0; padding-left: 1em; color: var(--text-sec); }
        
        code { background: var(--hover-bg); padding: 3px 6px; border-radius: 4px; font-family: monospace; font-size: 0.85em; color: #eb5757; }
        [data-theme="dark"] code { color: #ff9580; }
        
        /* 表格样式 */
        .table-wrapper {
            display: flex;
            justify-content: center;
            margin: 20px 0;
            overflow-x: auto;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            max-width: 800px;
        }
        th, td {
            border: 1px solid var(--border);
            padding: 8px 12px;
            text-align: center;
        }
        th {
            background-color: var(--hover-bg);
            font-weight: 600;
        }
        
        /* 任务列表样式 */
        ul.task-list {
            list-style-type: none;
            padding-left: 0;
        }
        ul.task-list li {
            list-style-type: none;
            padding-left: 0;
        }
        ul.task-list ul {
            list-style-type: none;
            padding-left: 20px;
        }
        
        /* 上下标样式 */
        sub, sup {
            font-size: 0.75em;
            line-height: 0;
            position: relative;
            vertical-align: baseline;
        }
        sub {
            bottom: -0.25em;
        }
        sup {
            top: -0.5em;
        }
    `;

    // 代码块样式 (Notion Style)
    const cssCodeBlocks = `
        .copy-code-button { display: none !important; }

        .code-block-container {
            position: relative;
            background: var(--code-bg);
            border-radius: var(--radius-md);
            margin: 16px 0;
            overflow: hidden;
            border: 1px solid transparent; 
        }
        [data-theme="dark"] .code-block-container { border-color: var(--border); }
        
        /* 操作栏 */
        .code-controls {
            position: absolute;
            top: 6px;
            right: 6px;
            display: flex;
            align-items: center;
            gap: 12px;
            opacity: 0;
            transition: opacity 0.2s ease;
            z-index: 10;
            background: var(--code-bg);
            padding-left: 8px;
            border-radius: 4px;
        }
        .code-block-container:hover .code-controls { opacity: 1; }
        
        /* 语言下拉框: 居中显示 */
        .lang-select {
            background: transparent; 
            border: 1px solid transparent;
            color: var(--text-sec); 
            font-size: 12px;
            cursor: pointer; outline: none; font-family: inherit;
            appearance: none; 
            font-weight: 500;
            padding: 4px 8px;
            border-radius: 4px;
            transition: all 0.1s;
            white-space: nowrap;
            text-align: center;      /* 文字居中 */
            text-align-last: center; /* 确保选中项居中 */
        }
        .lang-select:hover { background: var(--hover-bg); color: var(--text-main); }
        
        [data-theme="dark"] .lang-select { color-scheme: dark; color: #d4d4d4; }
        [data-theme="dark"] .lang-select option { background-color: #2a2a2a; color: #d4d4d4; }
        
        .lang-select::-webkit-scrollbar { width: 6px; height: 6px; }
        .lang-select::-webkit-scrollbar-track { background: transparent; }
        .lang-select::-webkit-scrollbar-thumb { background: rgba(0,0,0,0.1); border-radius: 3px; }
        .lang-select::-webkit-scrollbar-thumb:hover { background: rgba(0,0,0,0.2); }
        [data-theme="dark"] .lang-select::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.15); }

        /* 复制按钮 */
        .code-copy-btn {
            background: transparent; 
            border: 1px solid transparent;
            color: var(--text-sec); font-size: 12px;
            cursor: pointer; padding: 4px 8px;
            border-radius: 4px;
            display: flex; align-items: center; gap: 4px;
            font-family: inherit;
            transition: all 0.1s;
            white-space: nowrap;
        }
        .code-copy-btn:hover { background: var(--hover-bg); color: var(--text-main); }

        /* 代码区域 */
        .code-block-container pre {
            margin: 0 !important;
            padding: 34px 16px 16px !important;
            overflow-x: auto;
            background: transparent !important;
            border: none !important;
        }
        
        .code-block-container pre::-webkit-scrollbar { height: 6px; width: 6px; }
        .code-block-container pre::-webkit-scrollbar-track { background: transparent; }
        .code-block-container pre::-webkit-scrollbar-thumb { background: rgba(0,0,0,0.08); border-radius: 3px; }
        .code-block-container pre::-webkit-scrollbar-thumb:hover { background: rgba(0,0,0,0.15); }
        [data-theme="dark"] .code-block-container pre::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.1); }

        .code-block-container code {
            background: transparent !important;
            padding: 0 !important;
            border-radius: 0 !important;
            font-size: 13px;
            line-height: 1.6;
            color: var(--text-main);
            white-space: pre;
            font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace;
        }
    `;

    const cssAttachments = `
        .file-card {
            display: flex; flex-direction: row; align-items: center;
            background: var(--card-bg); border: 1px solid var(--card-border);
            border-radius: var(--radius-md); padding: 10px 14px; margin: 16px auto; 
            width: 320px; max-width: 100%;
            text-decoration: none !important; transition: all 0.2s; cursor: pointer;
            box-shadow: 0 1px 2px rgba(0,0,0,0.03); user-select: none;
        }
        .file-card:hover { border-color: var(--primary); box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08); transform: translateY(-1px); }
        
        .file-card .file-icon { font-size: 24px; color: var(--text-sec); margin-right: 12px; display: flex; align-items: center; }
        .file-card .file-info { flex: 1; min-width: 0; display: flex; flex-direction: column; justify-content: center; gap: 2px; }
        .file-card .file-name { font-weight: 700; font-size: 14px; color: var(--text-main); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; line-height: 1.3; }
        .file-card .file-meta { font-size: 11px; color: var(--text-sec); display: flex; align-items: center; opacity: 0.8; }
        
        .file-card .file-actions { display: flex; gap: 6px; margin-top: 6px; width: 100%; }
        .file-card button, .file-card .btn-download {
            background: transparent; border: 1px solid var(--border); border-radius: 4px;
            color: var(--text-sec); font-size: 11px; padding: 3px 0; line-height: 1.4;
            cursor: pointer; transition: all 0.1s; text-decoration: none !important;
            flex: 1; text-align: center; display: block;
        }
        .file-card button:hover, .file-card .btn-download:hover { background: var(--hover-bg); color: var(--text-main); border-color: var(--text-sec); }
        
        .file-download-icon { color: var(--text-sec); opacity: 0.6; margin-left: 12px; display: flex; align-items: center; }
        .file-card:hover .file-download-icon { opacity: 1; color: var(--primary); }

        .media-container { 
            display: flex; flex-direction: column; align-items: center; margin: 30px auto; width: 100%; max-width: 600px;
            background: var(--card-bg); padding: 16px; border-radius: var(--radius-md); border: 1px solid var(--card-border);
            box-shadow: 0 4px 12px rgba(0,0,0,0.05);
        }
        audio, video { width: 100%; outline: none; border-radius: 6px; }
        .media-caption { margin-top: 8px; font-size: 12px; color: var(--text-sec); text-align: center; }

        .pdf-preview-container embed { display: block; width: 100%; height: 800px; border-radius: var(--radius-md); border: 1px solid var(--border); margin-top: 10px; background: #fff; }
        .pdf-preview-container.active { display: block !important; animation: fadeIn 0.3s ease; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(-10px); } to { opacity: 1; transform: translateY(0); } }
    `;

    const cssUI = `
        .right-edge-bar { position: fixed; top: 0; bottom: 0; width: 24px; z-index: 50; pointer-events: auto; }
        .right-edge-bar.position-right { right: 0; }
        .right-edge-bar.position-left { left: 0; }
        /* 当文件列表显示且目录在左侧时，目录需要右移 */
        .layout-container:not(.hide-sidebar):not(.single-page) .right-edge-bar.position-left { left: 260px; }
        /* 单文件时目录在左侧边缘 */
        .layout-container.single-page .right-edge-bar.position-left { left: 0; }
        /* 响应式：小屏幕时目录始终在左侧 */
        @media (max-width: 768px) {
            .layout-container:not(.hide-sidebar):not(.single-page) .right-edge-bar.position-left { left: 0; }
        }
        .theme-toggle { position: fixed; top: 20px; right: 20px; width: 36px; height: 36px; display: flex; align-items: center; justify-content: center; border-radius: 50%; cursor: pointer; color: var(--text-sec); background: transparent; border: none; padding: 0; line-height: 0; z-index: 52; pointer-events: auto; transition: all 0.2s; }
        .theme-toggle:hover { background: var(--hover-bg); color: var(--text-main); transform: scale(1.05); }
        .theme-toggle svg { display: block; }

        .toc-trigger-container { position: absolute; top: 30vh; display: flex; flex-direction: column; align-items: flex-end; padding-right: 36px; gap: 14px; width: 100px; transition: all 0.3s ease; opacity: 1; pointer-events: auto; }
        .right-edge-bar.position-right .toc-trigger-container { right: 0; }
        .right-edge-bar.position-left .toc-trigger-container { left: 0; align-items: flex-start; padding-right: 0; padding-left: 36px; }
        .toc-trigger-container.centered { top: 50% !important; transform: translateY(-50%) !important; }
        .toc-line { height: 2px; background: var(--toc-line-inactive); border-radius: 2px; transition: background-color 0.2s; cursor: pointer; width: 16px; }
        .toc-line.level-1 { width: 24px; } .toc-line.level-2 { width: 18px; } .toc-line.level-3 { width: 14px; } .toc-line.level-4 { width: 10px; } .toc-line.level-5 { width: 8px; } .toc-line.level-6 { width: 6px; }
        .toc-line.active { background: var(--toc-line-active); }

        .toc-popover { position: fixed; top: 30vh; width: 220px; transform: translateY(-20%) scale(0.95); max-height: 60vh; background: var(--popover-bg); box-shadow: var(--popover-shadow); border-radius: var(--radius-md); padding: 8px; overflow-x: hidden; overflow-y: auto; opacity: 0; pointer-events: none; transition: all 0.25s cubic-bezier(0.25, 0.46, 0.45, 0.94); z-index: 51; }
        .right-edge-bar.position-right .toc-popover { right: 20px; transform: translateY(-20%) translateX(20px) scale(0.95); }
        .right-edge-bar.position-left .toc-popover { left: 20px; transform: translateY(-20%) translateX(-20px) scale(0.95); }
        /* 当文件列表显示且目录在左侧时，popover 需要右移 */
        .layout-container:not(.hide-sidebar):not(.single-page) .right-edge-bar.position-left .toc-popover { left: 280px; }
        /* 单文件时 popover 在左侧 */
        .layout-container.single-page .right-edge-bar.position-left .toc-popover { left: 20px; }
        .toc-popover::after { content: ""; position: absolute; top: 0; bottom: 0; width: 80px; z-index: -1; }
        .right-edge-bar.position-right .toc-popover::after { right: -60px; }
        .right-edge-bar.position-left .toc-popover::after { left: -60px; }
        .layout-container:not(.hide-sidebar) .right-edge-bar.position-left .toc-popover::after { left: 200px; }
        .toc-trigger-container:hover { opacity: 0; }
        .toc-trigger-container:hover + .toc-popover, .toc-popover:hover { opacity: 1; pointer-events: auto; transform: translateY(-20%) translateX(0) scale(1); }
        .right-edge-bar:has(.toc-popover:hover) .toc-trigger-container { opacity: 0; }

        .toc-link { display: block; padding: 8px 12px; color: var(--text-sec); font-size: 13px; text-decoration: none; border-radius: 6px; margin-bottom: 2px; line-height: 1.5; white-space: normal; word-break: break-word; transition: background 0.1s, color 0.1s; border-bottom: none !important; }
        .toc-link.level-1 { font-weight: 600; color: var(--text-main); margin-left: 0; } .toc-link.level-2 { margin-left: 12px; } .toc-link.level-3 { margin-left: 24px; font-size: 12px; } .toc-link.level-4 { margin-left: 36px; font-size: 12px; } .toc-link.level-5 { margin-left: 48px; font-size: 11px; } .toc-link.level-6 { margin-left: 60px; font-size: 11px; }
        .toc-link:hover { background: var(--hover-bg); color: var(--text-main); }
        .toc-link.active { color: var(--primary); background: transparent; font-weight: 500; }
        .toc-link.active:hover { background: var(--hover-bg); color: var(--primary); }

        #lightbox { position: fixed; inset: 0; background: rgba(0,0,0,0.9); display: none; align-items: center; justify-content: center; z-index: 1000; overflow: hidden; }
        #lightbox img { max-width: 90vw; max-height: 90vh; box-shadow: none; border-radius: 4px; cursor: grab; transition: transform 0.1s ease-out; transform-origin: center; will-change: transform; }
        #lightbox img:active { cursor: grabbing; }

        #mobile-menu-btn { display: none; }
        @media (max-width: 768px) {
            #sidebar { position: fixed; height: 100%; transform: translateX(-100%); box-shadow: 4px 0 12px rgba(0,0,0,0.1); }
            #sidebar.open { transform: translateX(0); }
            .right-edge-bar { display: flex !important; width: 30px; }
            .toc-trigger-container { width: 40px; padding-right: 10px; }
            .article-container { padding: 80px 24px; }
            #mobile-menu-btn { 
                position: fixed; top: 16px; left: 16px; 
                display: ${isSinglePage ? 'none' : 'flex'}; 
                align-items: center; justify-content: center;
                background: var(--bg-body); border: 1px solid var(--border);
                width: 40px; height: 40px; border-radius: 50%;
                box-shadow: 0 4px 12px rgba(0,0,0,0.1); z-index: 90;
                color: var(--text-sec); cursor: pointer;
            }
            .toc-popover.mobile-active {
                opacity: 1; pointer-events: auto;
                position: fixed !important; right: 40px !important; top: 20vh !important;
                z-index: 100; transform: scale(1) !important;
                border: 1px solid var(--border); box-shadow: 0 8px 30px rgba(0,0,0,0.15);
            }
            .theme-toggle { top: 16px; right: 16px; }
        }
    `;

    return `<!DOCTYPE html>
<html lang="zh-CN" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>${defaultTitle}</title>
    <script>
        (function() {
            const RESOURCES = {
                prismCss: { primary: 'https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism.min.css', fallback: 'https://unpkg.com/prismjs@1.29.0/themes/prism.min.css' },
                mathJax: { primary: 'https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js', fallback: 'https://unpkg.com/mathjax@3.2.2/es5/tex-mml-chtml.js' }
            };
            function loadCSS(config) {
                const link = document.createElement('link'); link.rel = 'stylesheet'; link.href = config.primary;
                link.onerror = function() { const fl = document.createElement('link'); fl.rel = 'stylesheet'; fl.href = config.fallback; document.head.appendChild(fl); };
                document.head.appendChild(link);
            }
            function loadJS(config) {
                const script = document.createElement('script'); script.src = config.primary; script.async = true;
                script.onerror = function() { const fs = document.createElement('script'); fs.src = config.fallback; fs.async = true; document.head.appendChild(fs); };
                document.head.appendChild(script);
            }
            window.MathJax = { 
                tex: { 
                    inlineMath: [['$', '$'], ['\\\\(', '\\\\)']],
                    displayMath: [['$$', '$$'], ['\\\\[', '\\\\]']]
                }, 
                svg: { fontCache: 'global' }, 
                startup: { pageReady: () => MathJax.startup.defaultPageReady() } 
            };
            loadCSS(RESOURCES.prismCss);
            loadJS(RESOURCES.mathJax);
        })();
    </script>
    <style>
        ${cssVariables}
        ${cssLayout}
        ${cssCodeBlocks}
        ${cssAttachments}
        ${cssUI}
    </style>
</head>
<body>
    <div id="mobile-menu-btn" onclick="app.toggleSidebar()">
        ${svgMenu}
    </div>

    <div class="layout-container ${settings.tocPosition === 'left' ? 'toc-left' : ''} ${isSinglePage ? 'single-page' : ''}">
        ${!isSinglePage ? `
        <aside id="sidebar">
            <div class="search-box">
                <input type="text" placeholder="搜索文档..." oninput="app.filter(this.value)">
            </div>
            <ul class="file-list" id="file-list-ul"></ul>
        </aside>
        ` : ''}

        <main id="main-scroll">
            <div class="article-container">
                ${settings.showTitle ? '<h1 id="page-title" class="page-title"></h1>' : ''}
                <div id="page-content"></div>
                ${settings.showFooter ? `<div style="margin-top: 80px; border-top: 1px solid var(--border); padding-top: 30px; text-align: center; color: var(--text-sec); font-size: 0.85em; white-space: pre-line;">${settings.footerText}</div>` : ''}
            </div>
        </main>

        ${settings.enableToc ? `
        <div class="right-edge-bar position-${settings.tocPosition}">
            <div class="toc-trigger-container" id="toc-lines"></div>
            <nav class="toc-popover" id="toc-popover-list"></nav>
        </div>
        ` : ''}
        
        ${!isSinglePage ? `
        <div class="sidebar-toggle" onclick="app.toggleSidebar()" title="显示文件列表">
            ${svgMenu}
        </div>
        ` : ''}
        
        <div class="theme-toggle" onclick="app.toggleTheme()" title="切换主题">
             <div id="theme-icon-container">${svgSun}</div>
        </div>
    </div>

    <div id="lightbox" onclick="app.closeLightbox(event)">
        <img id="lightbox-img">
    </div>

    <script>
        ${dataScript}
        const ICONS = { sun: '${svgSun}', moon: '${svgMoon}', copy: '${svgCopy}', check: '${svgCheck}' };

        const app = {
            data: WIKI_DATA,
            currentIdx: 0,
            observer: null,
            lightboxState: { scale: 1, isDragging: false, startX: 0, startY: 0, translateX: 0, translateY: 0 },
            isMobileTocOpen: false,
            isScrolling: false,

            init() {
                this.renderSidebar();
                this.loadState();
                
                // 监听窗口大小变化，调整大纲横线位置
                window.addEventListener('resize', () => {
                    const currentPage = this.data[this.currentIdx];
                    if (currentPage && currentPage.toc) {
                        this.updateTocContainerPosition(currentPage.toc.length);
                    }
                });
                
                // 1. 代码块: 复制
                document.getElementById('page-content').addEventListener('click', e => {
                    const btn = e.target.closest('.code-copy-btn');
                    if (btn) {
                        const wrapper = btn.closest('.code-block-container');
                        const code = wrapper.querySelector('code').innerText;
                        navigator.clipboard.writeText(code).then(() => {
                            const original = btn.innerHTML;
                            btn.innerHTML = ICONS.check + ' 已复制';
                            btn.dataset.copied = 'true';
                        });
                    }
                });

                // 2. 代码块: 鼠标移出重置
                document.getElementById('page-content').addEventListener('mouseout', e => {
                    const wrapper = e.target.closest('.code-block-container');
                    if (wrapper && !wrapper.contains(e.relatedTarget)) {
                        const btn = wrapper.querySelector('.code-copy-btn');
                        if (btn && btn.dataset.copied === 'true') {
                            btn.innerHTML = ICONS.copy + ' 复制';
                            delete btn.dataset.copied;
                        }
                    }
                });

                // 3. 语言切换
                document.getElementById('page-content').addEventListener('change', e => {
                    if (e.target.classList.contains('lang-select')) {
                        const wrapper = e.target.closest('.code-block-container');
                        const codeEl = wrapper.querySelector('code');
                        const newLang = e.target.value;
                        codeEl.className = 'language-' + newLang;
                        if (window.Prism) window.Prism.highlightElement(codeEl);
                    }
                });

                // 4. 右侧大纲点击
                const tocContainer = document.querySelector('.toc-trigger-container');
                if (tocContainer) {
                    tocContainer.addEventListener('click', (e) => {
                        if (window.innerWidth <= 768) {
                            this.toggleMobileToc(!this.isMobileTocOpen);
                            e.stopPropagation(); 
                        }
                    });
                }

                // 5. 图片点击
                document.getElementById('page-content').addEventListener('click', e => {
                    if(e.target.tagName === 'IMG') this.openLightbox(e.target.src);
                });

                // 6. PDF 按钮
                document.getElementById('page-content').addEventListener('click', e => {
                    if(e.target.classList.contains('btn-preview')) {
                        const card = e.target.closest('.file-card');
                        const wrapper = card.nextElementSibling;
                        if(wrapper && wrapper.classList.contains('pdf-preview-container')) {
                            if(wrapper.innerHTML === '') {
                                const src = card.dataset.src;
                                wrapper.innerHTML = \`<embed src="\${src}" type="application/pdf" />\`;
                                wrapper.classList.add('active');
                                e.target.innerText = '收起';
                            } else {
                                if(wrapper.classList.contains('active')) {
                                    wrapper.classList.remove('active');
                                    e.target.innerText = '预览';
                                } else {
                                    wrapper.classList.add('active');
                                    e.target.innerText = '收起';
                                }
                            }
                        }
                    }
                });

                // 7. 下载确认
                document.getElementById('page-content').addEventListener('click', e => {
                    const downloadLink = e.target.closest('a[download]') || e.target.closest('.btn-download');
                    if (downloadLink) {
                        e.preventDefault(); 
                        let fileName = 'file';
                        const card = downloadLink.closest('.file-card');
                        if (card) {
                            const nameEl = card.querySelector('.file-name');
                            if (nameEl) fileName = nameEl.innerText;
                        }
                        if (confirm(\`确认下载文件: \${fileName}?\`)) {
                            const href = downloadLink.getAttribute('href');
                            const a = document.createElement('a');
                            a.href = href;
                            a.download = '';
                            document.body.appendChild(a);
                            a.click();
                            document.body.removeChild(a);
                        }
                    }
                });

                // 8. 关闭遮罩
                document.addEventListener('mousedown', (e) => {
                    const popover = document.getElementById('toc-popover-list');
                    const trigger = document.querySelector('.toc-trigger-container');
                    if (this.isMobileTocOpen && !popover.contains(e.target) && !trigger.contains(e.target)) {
                        this.toggleMobileToc(false);
                    }
                    if (!e.target.closest('.toc-link')) {
                        const targets = document.querySelectorAll('.highlight-target');
                        if (targets.length > 0) targets.forEach(t => t.classList.remove('highlight-target'));
                    }
                });

                this.setupLightboxEvents();
            },

            toggleMobileToc(show) {
                const popover = document.getElementById('toc-popover-list');
                this.isMobileTocOpen = show;
                if (show) popover.classList.add('mobile-active');
                else popover.classList.remove('mobile-active');
            },

            renderSidebar() {
                const fileListEl = document.getElementById('file-list-ul');
                if (!fileListEl) return; // 单文件时没有文件列表
                fileListEl.innerHTML = this.data.map((p, i) =>
                    \`<li class="file-item" onclick="app.loadPage(\${i})" data-idx="\${i}">
                        ${svgFile}
                        <span>\${p.title}</span>
                    </li>\`
                ).join('');
            },

            loadPage(idx) {
                this.currentIdx = idx;
                const page = this.data[idx];
                if (!page) return; // 防止索引越界
                
                const titleEl = document.getElementById('page-title');
                if (titleEl) titleEl.innerText = page.title;
                const contentEl = document.getElementById('page-content');
                if (contentEl) contentEl.innerHTML = page.content;
                
                document.querySelectorAll('.file-item').forEach(el => el.classList.remove('active'));
                document.querySelector('.file-item[data-idx="' + idx + '"]')?.classList.add('active');
                
                this.renderToc(page.toc || []);
                const mainScroll = document.getElementById('main-scroll');
                if (mainScroll) mainScroll.scrollTop = 0;
                localStorage.setItem('wiki_last_idx', idx);
                
                if (window.innerWidth <= 768) {
                    const sidebar = document.getElementById('sidebar');
                    if (sidebar) sidebar.classList.remove('open');
                    this.toggleMobileToc(false);
                }

                setTimeout(() => {
                    if(page.toc && page.toc.length > 0) this.updateActiveToc(page.toc[0].id);
                    if (window.MathJax && window.MathJax.typesetPromise && contentEl) {
                        window.MathJax.typesetPromise([contentEl]).catch(err => console.log(err));
                    }
                    if (window.Prism && contentEl) {
                        window.Prism.highlightAllUnder(contentEl);
                    }
                }, 100);
            },

            renderToc(toc) {
                const linesContainer = document.getElementById('toc-lines');
                const popoverContainer = document.getElementById('toc-popover-list');
                
                if(!toc || !toc.length) {
                    linesContainer.innerHTML = '';
                    popoverContainer.innerHTML = '<div style="padding:10px;color:var(--text-sec);font-size:12px;text-align:center">暂无目录</div>';
                    return;
                }
                
                linesContainer.innerHTML = toc.map(h => \`<div class="toc-line level-\${h.level}" data-target="\${h.id}"></div>\`).join('');
                popoverContainer.innerHTML = toc.map(h => \`<a href="javascript:void(0)" onclick="app.scrollToHeader('\${h.id}')" class="toc-link level-\${h.level}" data-target="\${h.id}">\${h.text}</a>\`).join('');
                
                // 检测标题数量，决定是否居中显示大纲横线
                this.updateTocContainerPosition(toc.length);
                
                this.initScrollSpy();
            },
            
            updateTocContainerPosition(tocLength) {
                const linesContainer = document.getElementById('toc-lines');
                console.log('TOC Length:', tocLength);
                
                // 如果标题数量大于10，则居中显示
                if (tocLength > 10) {
                    linesContainer.classList.add('centered');
                    console.log('Added centered class');
                } else {
                    // 否则保持默认的偏上显示
                    linesContainer.classList.remove('centered');
                    console.log('Removed centered class');
                }
            },

            scrollToHeader(id) {
                console.log('scrollToHeader called for:', id);
                document.querySelectorAll('.highlight-target').forEach(t => t.classList.remove('highlight-target'));
                const target = document.getElementById(id);
                if(target) {
                    // 设置滚动标志，防止 IntersectionObserver 干扰
                    this.isScrolling = true;
                    console.log('Set isScrolling to true');
                    target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                    target.classList.add('highlight-target');
                    // 更新大纲高亮状态
                    this.updateActiveToc(id);
                    if (this.isMobileTocOpen) this.toggleMobileToc(false);
                    // 使用滚动事件检测滚动结束
                    this.waitForScrollEnd();
                }
            },
            
            waitForScrollEnd() {
                const mainScroll = document.getElementById('main-scroll');
                let scrollTimeout;
                
                const onScroll = () => {
                    clearTimeout(scrollTimeout);
                    scrollTimeout = setTimeout(() => {
                        // 滚动停止后重置标志
                        console.log('Scroll ended, setting isScrolling to false');
                        this.isScrolling = false;
                        mainScroll.removeEventListener('scroll', onScroll);
                    }, 150);
                };
                
                mainScroll.addEventListener('scroll', onScroll);
                // 安全机制：最多等待3秒后强制重置
                setTimeout(() => {
                    console.log('Safety timeout, setting isScrolling to false');
                    this.isScrolling = false;
                    mainScroll.removeEventListener('scroll', onScroll);
                }, 3000);
            },

            updateActiveToc(id) {
                document.querySelectorAll('.toc-line.active, .toc-link.active').forEach(l => l.classList.remove('active'));
                const activeLine = document.querySelector(\`.toc-line[data-target="\${id}"]\`);
                const activeLink = document.querySelector(\`.toc-link[data-target="\${id}"]\`);
                if(activeLine) activeLine.classList.add('active');
                if(activeLink) {
                    activeLink.classList.add('active');
                    if(window.innerWidth > 768 && getComputedStyle(document.querySelector('.toc-popover')).opacity === '1') {
                        activeLink.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
                    }
                }
            },

            initScrollSpy() {
                if(this.observer) this.observer.disconnect();
                const headers = document.querySelectorAll('#page-content h1, #page-content h2, #page-content h3, #page-content h4, #page-content h5, #page-content h6');
                if(headers.length === 0) return;
                this.observer = new IntersectionObserver(entries => {
                    // 如果正在手动滚动，不更新高亮状态
                    if (this.isScrolling) {
                        console.log('Skipping update because isScrolling is true');
                        return;
                    }
                    entries.forEach(entry => {
                        if (entry.isIntersecting) {
                            console.log('Updating TOC for:', entry.target.id);
                            this.updateActiveToc(entry.target.id);
                        }
                    });
                }, { root: document.getElementById('main-scroll'), rootMargin: "-10% 0px -70% 0px", threshold: 0 });
                headers.forEach(h => this.observer.observe(h));
            },

            toggleTheme() {
                const html = document.documentElement;
                const newTheme = html.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
                html.setAttribute('data-theme', newTheme);
                localStorage.setItem('wiki_theme', newTheme);
                this.updateThemeIcon(newTheme);
            },

            updateThemeIcon(theme) {
                document.getElementById('theme-icon-container').innerHTML = theme === 'dark' ? ICONS.moon : ICONS.sun;
            },

            loadState() {
                const theme = localStorage.getItem('wiki_theme') || 'light';
                document.documentElement.setAttribute('data-theme', theme);
                this.updateThemeIcon(theme);
                const lastIdx = localStorage.getItem('wiki_last_idx');
                this.loadPage(lastIdx ? parseInt(lastIdx) : 0);
            },
            
            filter(val) {
                document.querySelectorAll('.file-item').forEach(item => {
                    const idx = item.getAttribute('data-idx');
                    item.style.display = this.data[idx].title.toLowerCase().includes(val.toLowerCase()) ? 'flex' : 'none';
                });
            },

            toggleSidebar() {
                const container = document.querySelector('.layout-container');
                if (container) {
                    container.classList.toggle('hide-sidebar');
                }
            },

            setupLightboxEvents() {
                const img = document.getElementById('lightbox-img');
                const lb = document.getElementById('lightbox');
                lb.addEventListener('wheel', (e) => {
                    e.preventDefault();
                    const delta = e.deltaY > 0 ? 0.9 : 1.1;
                    let newScale = this.lightboxState.scale * delta;
                    newScale = Math.min(Math.max(0.5, newScale), 5);
                    this.lightboxState.scale = newScale;
                    this.updateLightboxTransform();
                });
                img.addEventListener('mousedown', (e) => {
                    e.preventDefault();
                    this.lightboxState.isDragging = true;
                    this.lightboxState.startX = e.clientX - this.lightboxState.translateX;
                    this.lightboxState.startY = e.clientY - this.lightboxState.translateY;
                });
                window.addEventListener('mousemove', (e) => {
                    if (!this.lightboxState.isDragging) return;
                    this.lightboxState.translateX = e.clientX - this.lightboxState.startX;
                    this.lightboxState.translateY = e.clientY - this.lightboxState.startY;
                    this.updateLightboxTransform();
                });
                window.addEventListener('mouseup', () => { this.lightboxState.isDragging = false; });
            },
            updateLightboxTransform() {
                const img = document.getElementById('lightbox-img');
                img.style.transform = \`translate(\${this.lightboxState.translateX}px, \${this.lightboxState.translateY}px) scale(\${this.lightboxState.scale})\`;
            },
            openLightbox(src) {
                const lb = document.getElementById('lightbox');
                const img = document.getElementById('lightbox-img');
                img.src = src;
                lb.style.display = 'flex';
                this.lightboxState = { scale: 1, isDragging: false, startX: 0, startY: 0, translateX: 0, translateY: 0 };
                this.updateLightboxTransform();
            },
            closeLightbox(e) {
                if (e.target.id === 'lightbox') { e.target.style.display = 'none'; }
            }
        };
        app.init();
    </script>
</body>
</html>`;
}